import { readFile } from 'node:fs/promises';
import { runInNewContext } from 'node:vm';
export const cases = [];
const add = (category, id, code, extra = {}) => cases.push({ id: `${category}-${id}`, category, feature: id, code, input: [], files: [], ...extra });
const exprs = (category, rows) => rows.forEach(([id, expression, extra]) => add(category, id, `print(${expression})`, extra));
const scripts = (category, rows) => rows.forEach(([id, code, extra]) => add(category, id, code, extra));
const intentional = notes => ({ policy: 'intentional-difference', notes });
const unsupported = notes => ({ policy: 'unsupported', notes });
// Reuse the exact 52 existing source cases, without executing or changing that script.
const legacy = await readFile('scripts/compare-core-v2.mjs', 'utf8');
const literal = legacy.slice(legacy.indexOf('  const cases = [') + '  const cases = '.length, legacy.indexOf('\n  for (const [name, source'));
const old = runInNewContext(literal.replace(/;\s*$/, ''));
if (old.length !== 52) throw Error('Expected 52 legacy cases');
for (const [index, [name, code, , files]] of old.entries()) add('legacy', String(index + 1).padStart(2, '0'), code, { feature: name, files: Object.entries(files ?? {}).map(([name, content]) => ({ name, content })), legacy: true });
// Each expression below is a distinct boundary/operation, not counted in several categories.
exprs('numeric', [
  ...['0','1','-1','2**31-1','2**31','2**53-1','2**53','2**53+1','10**20','10**100'].map((s,i) => [`integer-${i}`, s, i >= 6 ? intentional('문서화된 ±(2**53-1) 정수 정밀도 범위 밖') : {}]),
  ...['-7//3','-7%3','7//-3','7%-3','-7//-3','-7%-3','7/2','4.0//2','-7.0%3','1+2.0','1.0-2','-2*3','2**-3','pow(2,10)','pow(2,10,17)','pow(3,-1,11)','pow(2,3,-5)','divmod(-7,3)','abs(-0.0)','round(2.5)','round(3.5)','round(1.25,1)','round(2.675,2)','round(1250,-2)','round(-2.5)','round(1.0)','round(1.0,0)','0.0','-0.0','0.1+0.2','1e-300','1e300','float("inf")','float("-inf")','float("nan")','float("nan")==float("nan")','bool(float("nan"))','1/0','1.0/0.0','0//0','0%0','0**-1','pow(2,3,0)','pow(2,-1,4)','float("x")','int("10.0")','int("")','int("0x10")','int(float("inf"))','int(float("nan"))','int(-1.9)','float(None)','round(float("inf"))','round(float("nan"))','divmod(1.0,0.1)','1.0//0.1','-0.0%3.0','1e-5','1e16','1e15'].map((s,i) => [`operation-${i}`,s, { numeric: true }]),
  ...[9007199254740990n,9007199254740991n,9007199254740992n,9007199254740993n,9007199254740994n,9007199254740995n].map(n => [`boundary-${n}`,String(n), n > 9007199254740991n ? intentional('안전 정수 범위 밖의 연속 정수 리터럴') : {}]),
]);
const mark = 'events = []\ndef mark(name, value):\n    events.append(name)\n    return value\n';
for (const [id, body] of [
  ['binary','print(mark("left", 1) + mark("right", 2))'],
  ['call-object','def f(x):\n    return x\nprint(mark("function", f)(mark("arg", 2)))'],
  ['positional','print(mark("a", 1), mark("b", 2))'],
  ['keywords','def f(a,b):\n    return a+b\nprint(f(b=mark("b",2),a=mark("a",1)))'],
  ['stars','def f(*a,**k):\n    print(a,k)\nf(*mark("args",[1]), **mark("kwargs",{"x":2}))'],
  ['list','print([mark("a",1),mark("b",2)])'], ['tuple','print((mark("a",1),mark("b",2)))'],
  ['dict','print({mark("k1","x"):mark("v1",1),mark("k2","x"):mark("v2",2)})'],
  ['set','print(sorted({mark("a",2),mark("b",1)}))'],
  ['index','print(mark("object",[10])[mark("index",0)])'],
  ['slice','print(mark("object",[0,1,2,3])[mark("start",0):mark("stop",3):mark("step",2)])'],
  ['assign','a=[0]\nmark("container",a)[mark("index",0)]=mark("rhs",5)\nprint(a)'],
  ['chain','a=[0,0]\nmark("first",a)[0]=mark("second",a)[1]=mark("rhs",7)\nprint(a)'],
  ['unpack','a=[0,0]\nmark("first",a)[0],mark("second",a)[1]=mark("rhs",[8,9])\nprint(a)'],
  ['augmented','a=[[1]]\nmark("outer",a)[mark("i",0)][mark("j",0)] += mark("rhs",2)\nprint(a)'],
  ['compare','print(mark("a",1)<mark("b",2)<mark("c",3))'],
  ['compare-short','print(mark("a",3)<mark("b",2)<mark("c",1))'],
  ['and','print(mark("a",0) and mark("b",1))'],['or','print(mark("a",1) or mark("b",2))'],
  ['conditional','print(mark("yes",1) if mark("condition",True) else mark("no",2))'],
  ['list-comp','print([mark("element",x) for x in mark("iterable",[1,2]) if mark("filter",x>1)])'],
  ['dict-comp','print({mark("key",x):mark("value",x+1) for x in [1,2]})'],
  ['set-comp','print(sorted({mark("element",x) for x in [1,2]}))'],
  ['default','def f(a=mark("default",3)):\n    return a\nprint(f(),f())'],
  ['finally','def f():\n    try:\n        return mark("return",1)\n    finally:\n        mark("finally",0)\nprint(f())'],
  ['keyword-before-star','def f(*a,**k):\n    print(a,k)\nf(x=mark("kw",1),*mark("star",[2]))'],
]) add('evaluation', id, mark + body + '\nprint(events)');
exprs('comparison', ['None==None','None is None','True is True','True==1','False==0.0','1==1.0','1<2<=2','[1,2]<[1,3]','(1,2)<(1,3)','[1]==(1,)','{"a":1}=={"a":1}','{1,2}=={2,1}','1 in [True]','2 not in (1,)','"😀" in "가😀"','1 < "2"','None < 1','{1} < {1,2}','{1} <= {1}','{} < {}','not []','bool(range(0))','bool(range(1))'].map((s,i)=>[`value-${i}`,s]));
for (const [id, setup] of [['list','[]'],['dict','{}'],['set','set()'],['iterator','zip([1],[2])'],['builtin','int']]) add('comparison',`identity-${id}`,`a=${setup}\nb=a\nc=${setup}\nprint(a is b, a is c)`);
scripts('comparison', [['function','def f():\n    pass\na=f\nprint(a is f)'],['class','class A:\n    pass\nprint(A is A, A() is A())'],['instance','class A:\n    pass\na=A()\nb=a\nprint(a is b)'],['module','import math\nimport math as m\nprint(math is m)'],['interning','a=int("1000")\nb=int("1000")\nprint(a is b)',intentional('CPython 정수 캐싱/객체 동일성 최적화는 복제하지 않음')]]);
exprs('string', [
  ...['""','"한글"+"수업"','"가"*3','"가😀나"[1]','"가😀나"[-1]','"가😀나"[::-1]','"가😀나"[::2]','len("가😀나")','len("é")','"😀"<"𐀀"','"a\\tb\\nc"','"a\\\\b"','"abc"[9]','"".join(["가","나"])','"a".join([1])','"banana".find("an",2,5)','"banana".rfind("an")','"abc".index("z")','"abc".find("z")','"abc".count("",4)','"abc".startswith(("a","b"))','"abc".endswith("c")','" ABC ".lower()','"straße".upper()','"hELLO".capitalize()','"they\'re here".title()','"한글".isalpha()','"²".isdigit()','"Ⅻ".isalnum()','"\u200b".isspace()','"\u001c".isspace()','"".isspace()','"  x ".lstrip()','"  x ".rstrip()','"xy가yx".strip("xy")','" a  b ".split()','"a,,b,".split(",")','"a,b,c".rsplit(",",1)','"a".split("")','"aaaa".replace("a","x",2)','"a".center(4,"-")','"abc".ljust(2)','"가".rjust(4,".")','"-12".zfill(5)','"abc".find(1)','"x".upper(1)','"İ".lower()','"ǰ".upper()','"ǅ".title()','"𝟙".isdigit()','"é".isalpha()'].map((s,i)=>[`operation-${i}`,s]),
]);
scripts('collection', [
 ['list-copy','a=[[1]]\nb=a.copy()\nb[0].append(2)\nprint(a,b,a is b)'],['tuple-create','print(tuple([1,2]))'],['list-create','print(list("가😀"))'],['list-concat','print([1]+[2])'],['tuple-repeat','print((1,2)*2)'],['list-ref','a=[]\nb=[a,a]\nb[0].append(1)\nprint(b)'],['list-negative','a=[1,2]\nprint(a[-1])'],['list-index-error','print([1][2])'],['list-append','a=[]\nprint(a.append(1),a)'],['list-extend','a=[1]\na.extend((2,3))\nprint(a)'],['list-insert','a=[1]\na.insert(-99,2)\nprint(a)'],['list-remove','a=[1,2,1]\nprint(a.remove(1),a)'],['list-remove-error','a=[]\na.remove(1)'],['list-pop','a=[1,2]\nprint(a.pop(0),a)'],['list-pop-empty','a=[]\na.pop()'],['list-clear','a=[1]\nprint(a.clear(),a)'],['list-index','print([1,2,1].index(1,1))'],['list-count','print([1,True,1.0].count(1))'],['list-reverse','a=[1,2]\nprint(a.reverse(),a)'],['list-sort-stable','a=[("a",1),("b",1),("c",0)]\na.sort(key=lambda x:x[1],reverse=True)\nprint(a)'],['list-sort-key','events=[]\ndef key(x):\n    events.append(x)\n    return x\na=[3,1,2]\na.sort(key=key)\nprint(events,a)'],['list-sort-mixed','print(sorted([1,"a"]))'],['list-sort-key-error','def key(x):\n    return missing\nprint(sorted([1],key=key))'],['list-mutation-iteration','a=[1,2,3]\nfor x in a:\n    if x==1:\n        a.append(4)\n    print(x)'],
 ['dict-order','d={"a":1,"b":2}\nd["a"]=3\nprint(d)'],['dict-bool-key','d={True:"a",1:"b",1.0:"c"}\nprint(d)'],['dict-unhashable','d={[1]:2}'],['dict-nan-key','x=float("nan")\nd={x:1}\nprint(d[x])'],['dict-keys','print(list({"a":1}.keys()))'],['dict-values','print(list({"a":1}.values()))'],['dict-items','print(list({"a":1}.items()))'],['dict-get','print({"a":None}.get("a",2))'],['dict-setdefault','d={}\na=d.setdefault("x",[])\na.append(1)\nprint(d)'],['dict-update-pairs','d={}\nd.update([("a",1)],b=2)\nprint(d)'],['dict-pop-default','print({}.pop("x",3))'],['dict-pop-error','{}.pop("x")'],['dict-popitem','d={"a":1,"b":2}\nprint(d.popitem(),d)'],['dict-popitem-empty','{}.popitem()'],['dict-clear','d={1:2}\nprint(d.clear(),d)'],['dict-copy','a={"x":[]}\nb=a.copy()\nb["x"].append(1)\nb["x"]=2\nprint(a,b)'],['dict-fromkeys','d=dict.fromkeys([1,2],[])\nd[1].append(3)\nprint(d)'],['dict-modification','d={1:1,2:2}\nfor x in d:\n    d[3]=3\nprint(d)'],['dict-merge','print({**{"a":1},**{"a":2}})'],['dict-view','d={1:2}\nv=d.keys()\nd[3]=4\nprint(list(v))',intentional('문서화된 dict keys/values/items 스냅샷, 동적 view 미지원')],
 ['set-dedupe','print(sorted({1,True,1.0,2}))'],['set-order','print({"가","나","다"})',{semantic:'set',notes:'집합 repr 순서는 보장되지 않음'}],['set-union','print(sorted({1,2}|{2,3}))'],['set-intersect','print(sorted({1,2}&{2,3}))'],['set-difference','print(sorted({1,2}-{2,3}))'],['set-symmetric','print(sorted({1,2}^{2,3}))'],['set-unhashable','set([[1]])'],['set-pop','s={"가","나"}\nx=s.pop()\nprint(x not in s,len(s))'],['set-equal','print({1,2}=={2,1})'],['set-subset','print({1}<{1,2})'],['set-modification','s={1,2}\nfor x in s:\n    s.add(3)\nprint(sorted(s))'],['set-add','s=set()\ns.add(1)\nprint(sorted(s))'],['set-discard','s={1}\ns.discard(2)\nprint(sorted(s))'],['set-remove-error','s=set()\ns.remove(1)'],['tuple-immutable','a=(1,2)\na[0]=3'],
]);
exprs('assignment', ['[0,1,2,3][::-1]','[0,1,2,3][::2]','[0,1,2,3][100::-1]','[0,1,2,3][:-100:-1]','[1,2][::0]','"가😀나"[1:3]','(1,2,3)[::-1]'].map((s,i)=>[`slice-${i}`,s]));
scripts('assignment', [
 ['chain-ref','a=b=[]\na.append(1)\nprint(a,b)'],['chain-input','a=b=input("값:")\nprint(a,b)',{input:['7']}],['chain-subscript','a=[0,0]\nv=a[0]=a[1]=3\nprint(v,a)'],['tuple-unpack','a,b=1,2\nprint(a,b)'],['list-unpack','[a,b]=[1,2]\nprint(a,b)'],['nested','a,(b,c)=[1,[2,3]]\nprint(a,b,c)'],['star-middle','a,*b,c=range(5)\nprint(a,b,c)'],['star-start','*a,b=[1,2,3]\nprint(a,b)'],['star-end','a,*b=[1]\nprint(a,b)'],['too-few','a,b=[1]'],['too-many','a,b=[1,2,3]'],['subscript-unpack','a=[0,0]\na[0],a[1]=[1,2]\nprint(a)'],['mixed','a=[0]\nx,a[0]=1,2\nprint(x,a)'],['unpack-partial','a=b=9\ntry:\n    a,b=[1]\nexcept ValueError:\n    print(a,b)'],['nested-partial','a=b=c=9\ntry:\n    a,(b,c)=[1,[2]]\nexcept ValueError:\n    print(a,b,c)'],['target-ltr','i=0\na=[0,0]\ni,a[i]=1,2\nprint(a)'],['bad-target','1=x'],['del-name','a=1\ndel a\nprint(a)'],['del-index','a=[1,2]\ndel a[-1]\nprint(a)'],['del-slice','a=[0,1,2,3]\ndel a[::2]\nprint(a)'],['slice-assign','a=[0,1,2,3]\na[1:3]=[8]\nprint(a)'],['step-assign','a=[0,1,2,3]\na[::2]=[8,9]\nprint(a)'],['step-size','a=[0,1,2,3]\na[::2]=[8]'],['aug-list-ref','a=[1]\nb=a\na += [2]\nprint(a,b,a is b)'],['aug-nested','a=[[1]]\na[0][0]+=2\nprint(a)'],['slice-float','print([1,2][1.0:])'],['index-bool','print([1,2][True])'],
]);
scripts('control', [
 ['if','if True:\n    print(1)'],['elif','if False:\n    print(0)\nelif True:\n    print(1)\nelse:\n    print(2)'],['if-empty','if []:\n    print(0)\nelse:\n    print(1)'],['while','n=3\nwhile n:\n    print(n)\n    n-=1'],['while-empty','while False:\n    print(0)\nelse:\n    print(1)'],['while-break','while True:\n    break\nelse:\n    print(1)'],['while-continue','n=0\nwhile n<3:\n    n+=1\n    if n<3:\n        continue\n    print(n)'],['for-empty','for x in []:\n    print(x)\nelse:\n    print(1)'],['for-complete','for x in [1,2]:\n    print(x)\nelse:\n    print(3)'],['for-break','for x in [1]:\n    break\nelse:\n    print(1)'],['for-continue','for x in [1,2]:\n    continue\nelse:\n    print(3)'],['nested-break','for x in [1,2]:\n    for y in [1]:\n        break\nelse:\n    print(3)'],['break-finally','for x in [1]:\n    try:\n        break\n    finally:\n        print(2)'],['continue-finally','for x in [1,2]:\n    try:\n        continue\n    finally:\n        print(x)'],['pass','pass'],['conditional-lazy','print(1 if True else missing)'],['dict-iteration','for k in {"a":1,"b":2}:\n    print(k)'],['string-iteration','for k in "가😀":\n    print(k)'],['range-negative','print(list(range(3,-1,-1)))'],['range-zero','range(1,2,0)'],['for-noniterable','for x in 1:\n    pass'],['break-outside','break'],['continue-outside','continue'],['return-outside','return 1'],['comp-no-leak','x=10\na=[x for x in range(2)]\nprint(x,a)'],['comp-scope','a=[x for x in range(2)]\nprint(x)'],['comp-nested','print([[x*y for x in range(2)] for y in range(2)])'],['comp-filter','print([x for x in range(5) if x%2])'],['comp-multifor','print([(x,y) for x in [1,2] for y in [3,4]])'],
]);
scripts('function', [
 ['positional','def f(x):\n    return x+1\nprint(f(2))'],['keyword','def f(x,y):\n    return x-y\nprint(f(y=1,x=3))'],['default','def f(x=3):\n    return x\nprint(f())'],['mutable-default','def f(a=[]):\n    a.append(1)\n    return a\nprint(f())\nprint(f())'],['args','def f(*a):\n    return a\nprint(f(1,2))'],['kwargs','def f(**k):\n    return k\nprint(f(x=1,y=2))'],['duplicate','def f(x):\n    pass\nf(1,x=2)'],['missing','def f(x):\n    pass\nf()'],['excess','def f(x):\n    pass\nf(1,2)'],['unknown','def f(x):\n    pass\nf(z=1)'],['lambda','f=lambda x:x*2\nprint(f(3))'],['lambda-default','f=lambda x=3:x+1\nprint(f())'],['function-value','def f(x):\n    return x\ng=f\nprint(g(2),g is f)'],['map-function','def f(x):\n    return x+1\nprint(list(map(f,[1,2])))'],['sorted-function','print(sorted([1,3,2],key=lambda x:-x))'],['local-before-assignment','x=1\ndef f():\n    print(x)\n    x=2\nf()'],['global','x=1\ndef f():\n    global x\n    x=2\nf()\nprint(x)'],['nonlocal','def outer():\n    x=1\n    def inner():\n        nonlocal x\n        x+=1\n        return x\n    return inner\nf=outer()\nprint(f(),f())'],['closure-late','fs=[]\nfor x in range(3):\n    fs.append(lambda:x)\nprint([f() for f in fs])'],['closure-nested','def a(x):\n    def b(y):\n        return lambda z:x+y+z\n    return b\nprint(a(1)(2)(3))'],['recursive','def f(n):\n    return 1 if n<2 else n*f(n-1)\nprint(f(6))'],['indirect','def even(n):\n    return True if n==0 else odd(n-1)\ndef odd(n):\n    return False if n==0 else even(n-1)\nprint(even(8))'],['recursive-error','def f(n):\n    if n==0:\n        raise ValueError("x")\n    return f(n-1)\nf(3)'],['recursive-input','def f(n):\n    if n==0:\n        return int(input("数:"))\n    return n+f(n-1)\nprint(f(2))',{input:['4']}],['default-eval-once','x=1\ndef f(a=x):\n    return a\nx=2\nprint(f())'],['args-expansion','def f(a,b):\n    return a+b\nprint(f(*[1,2]))'],['kwargs-expansion','def f(a,b):\n    return a+b\nprint(f(**{"a":1,"b":2}))'],['kwargs-non-string','def f(**k):\n    pass\nf(**{1:2})'],['invalid-nonlocal','def f():\n    nonlocal missing\nf()'],['global-order','def f():\n    print(x)\n    global x\nx=1\nf()'],['keyword-only','def f(*,x):\n    return x\nprint(f(x=3))'],['return-none','def f():\n    pass\nprint(f())'],['return-finally','def f():\n    try:\n        return 1\n    finally:\n        print("f")\nprint(f())'],['map-except','def f(x):\n    try:\n        return 1/x\n    except ZeroDivisionError:\n        return 0\nprint(list(map(f,[0,1])))'],['parameter-shadow','x=1\ndef f(x):\n    return x\nprint(f(2),x)'],
]);
for (const n of [126,127,128,129,130,990,1000]) add('function',`depth-${n}`,`def f(n):\n    return 0 if n==0 else f(n-1)+1\nprint(f(${n}))`, intentional('VM 최대 호출 프레임 128, CPython 기본 재귀 제한 1000; oracle 래퍼 프레임 포함'));
scripts('exception', [
 ['value','raise ValueError("x")'],['type','raise TypeError("x")'],['assert','assert False,"x"'],['assert-pass','assert True\nprint(1)'],['zero','print(1/0)'],['name','print(missing)'],['index','print([][0])'],['key','print({}["x"])'],['catch','try:\n    print(1/0)\nexcept ZeroDivisionError:\n    print(1)'],['bare','try:\n    print(1/0)\nexcept:\n    print(1)'],['multi','try:\n    raise ValueError("x")\nexcept TypeError:\n    print(0)\nexcept ValueError:\n    print(1)'],['else','try:\n    print(1)\nexcept Exception:\n    print(0)\nelse:\n    print(2)'],['finally-normal','try:\n    print(1)\nfinally:\n    print(2)'],['finally-error','try:\n    raise ValueError("x")\nfinally:\n    print(2)'],['finally-replace','try:\n    raise ValueError("x")\nfinally:\n    raise TypeError("y")'],['finally-return','def f():\n    try:\n        raise ValueError("x")\n    finally:\n        return 2\nprint(f())'],['reraise','try:\n    raise ValueError("x")\nexcept ValueError:\n    raise'],['reraise-outside','raise'],['as-clear','try:\n    1/0\nexcept ZeroDivisionError as e:\n    pass\nprint(e)'],['as-overwrite','e=1\ntry:\n    1/0\nexcept ZeroDivisionError as e:\n    pass\nprint(e)'],['as-break','for x in [1]:\n    try:\n        1/0\n    except ZeroDivisionError as e:\n        break\nprint(e)'],['as-continue','for x in [1]:\n    try:\n        1/0\n    except ZeroDivisionError as e:\n        continue\nprint(e)'],['as-inner-loop','try:\n    1/0\nexcept ZeroDivisionError as e:\n    for x in [1]:\n        continue\n    print(1)'],['as-new-error','try:\n    try:\n        1/0\n    except ZeroDivisionError as e:\n        missing\nexcept NameError:\n    pass\nprint(e)'],['frame','def f():\n    raise ValueError("x")\ntry:\n    f()\nexcept ValueError:\n    print(1)'],['with-clean','try:\n    with open("a.txt","w") as f:\n        f.write("x")\n        raise ValueError("x")\nexcept ValueError:\n    print(f.closed)'],['nested-handler','try:\n    1/0\nexcept ZeroDivisionError as outer:\n    try:\n        missing\n    except NameError as inner:\n        pass\n    print(1)\nprint(inner)'],['exception-string','try:\n    1/0\nexcept ZeroDivisionError as e:\n    print(str(e))',intentional('학생용 한국어 예외 메시지')],['raise-number','raise 1'],['raise-class','raise ValueError'],['finally-break-override','for x in [1]:\n    try:\n        raise ValueError("x")\n    finally:\n        break\nprint(1)'],['else-error','try:\n    pass\nexcept ValueError:\n    print(0)\nelse:\n    raise ValueError("x")'],
]);
const A='class A:\n    value=1\n    def __init__(self,x=3):\n        self.x=x\n    def f(self,y=2):\n        return self.x+y\n';
for (const [id,tail] of [['empty','print(A().x)'],['class-read','print(A.value)'],['class-write','A.value=2\nprint(A.value)'],['fallback','print(A().value)'],['shadow','a=A()\na.value=8\nA.value=9\nprint(a.value,A().value)'],['init-pos','print(A(5).x)'],['init-key','print(A(x=5).x)'],['instance-write','a=A()\na.x=8\nprint(a.x)'],['missing','print(A().missing)'],['missing-class','print(A.missing)'],['bound','a=A()\nf=a.f\nprint(f(4))'],['direct','print(A.f(A(),4))'],['default-method','print(A().f())'],['keyword-method','print(A().f(y=4))'],['method-missing','A.f()'],['method-extra','A().f(1,2)'],['init-extra','A(1,2)'],['init-duplicate','A(1,x=2)'],['objects-container','a=A()\nb=[a]\nc={"a":a}\nb[0].x=9\nprint(c["a"].x)'],['reference','a=A()\nb=a\nprint(a is b, a is A())'],['nested','a=A()\na.child=A(9)\nprint(a.child.x)']]) add('class',id,A+tail);
scripts('class', [['pass','class Empty:\n    pass\nprint(Empty is Empty)'],['str','class A:\n    def __str__(self):\n        return "가"\nprint(A())'],['str-invalid','class A:\n    def __str__(self):\n        return 1\nprint(A())'],['init-invalid','class A:\n    def __init__(self):\n        return 1\nA()'],['inherited',A+'class B(A):\n    pass\nprint(B().f(),B.value)'],['override',A+'class B(A):\n    def f(self):\n        return super().f()+1\nprint(B().f())'],['super-init',A+'class B(A):\n    def __init__(self,x):\n        super().__init__(x=x)\nprint(B(7).x)'],['isinstance',A+'class B(A):\n    pass\nprint(isinstance(B(),A),isinstance(A(),B))'],['issubclass',A+'class B(A):\n    pass\nprint(issubclass(B,A),issubclass(A,B))'],['bad-parent','class A(1):\n    pass'],['super-outside','super()'],['default-repr','class A:\n    pass\nprint(A())',{policy:'educational-compatible',notes:'기본 객체 표현은 호스트 메모리 주소를 노출하지 않는 교육용 표현'}],['multiple','class A:\n    pass\nclass B:\n    pass\nclass C(A,B):\n    pass',unsupported('다중 상속')],['decorator','def deco(f):\n    return f\n@deco\ndef f():\n    return 1\nprint(f())',unsupported('데코레이터')],['property','class A:\n    x=property(lambda self:3)\nprint(A().x)',unsupported('property')],['descriptor','class D:\n    def __get__(self,obj,cls):\n        return 3\nclass A:\n    x=D()\nprint(A().x)',unsupported('descriptor; 조용한 비호환 실행 여부 확인')],['metaclass','class A(metaclass=type):\n    pass',unsupported('메타클래스')],['operator-overload','class A:\n    def __add__(self,other):\n        return 3\nprint(A()+A())',unsupported('사용자 연산자 오버로딩')]]);
exprs('builtin', ['int("10")','float("1.5")','str(None)','bool([])','len((1,2))','list(range(3))','tuple("가나")','dict(a=1)','set([1,1])','sum([1,2])','min([1,2])','max(1,2)','abs(-1)','round(2.5)','pow(2,3)','divmod(7,3)','chr(128512)','ord("😀")','bin(-10)','oct(-10)','hex(-10)','list(enumerate(["a"],start=2))','list(zip([1,2],[3]))','list(zip())','list(reversed([1,2]))','any([])','all([])','sorted([3,1,2],reverse=True)','len(map(int,["1"]))','ord("")','chr(1114112)','enumerate([],1.0)','reversed({1})','zip(1)','sum([],None)','min([])','max([])','next(iter([1]))'].map((s,i)=>[`call-${i}`,s,i===37 ? unsupported('iter/next は Core v2 明示内장 목록 밖; StopIteration 연결 확인') : {}]));
scripts('builtin',[['map-consume','it=map(int,["1","2"])\nprint(list(it),list(it))'],['zip-consume','it=zip([1],[2])\nprint(list(it),list(it))'],['reverse-consume','it=reversed([1,2])\nprint(list(it),list(it))'],['any-lazy','def f(x):\n    print(x)\n    return x\nprint(any(map(f,[1,2])))'],['all-lazy','def f(x):\n    print(x)\n    return x\nprint(all(map(f,[0,1])))'],['iterator-nested','print(list(enumerate(zip([1,2],[3,4]))))'],['map-input','def f(x):\n    return input("값:")\nprint(list(map(f,[1])))',{input:['a'],...intentional('문서화된 map 내부 input 미지원')}],['map-bound','class A:\n    def f(self,x):\n        return x+1\nprint(list(map(A().f,[1,2])))'],['type','print(type(1))'],['range-repr','print(range(3))']]);
const helper={name:'helper.py',content:'value=3\ndef add(a,b):\n    return a+b\nclass Box:\n    def __init__(self,x):\n        self.x=x\ndef rec(n):\n    return n if n<2 else n*rec(n-1)'};
scripts('module', [['plain','import helper\nprint(helper.value)',{files:[helper]}],['alias','import helper as h\nprint(h.add(1,2))',{files:[helper]}],['from','from helper import add\nprint(add(1,2))',{files:[helper]}],['from-alias','from helper import add as plus\nprint(plus(1,2))',{files:[helper]}],['cache','import helper\nimport helper as h\nprint(h is helper)',{files:[{name:'helper.py',content:'print("init")'}]}],['globals','value=9\nimport helper\nprint(value,helper.value)',{files:[helper]}],['names','import helper\nprint(__name__,helper.__name__)',{files:[helper]}],['missing','import nonexistent_audit_module',intentional('없는 모듈은 문서화된 ImportError로 연결, CPython ModuleNotFoundError와 구분')],['missing-member','from helper import missing',{files:[helper]}],['circular','import one',{files:[{name:'one.py',content:'import two'},{name:'two.py',content:'import one'}],...intentional('기본 순환 import를 차단; CPython 부분 초기화 캐시와 다름')}],['class','import helper\nprint(helper.Box(3).x)',{files:[helper]}],['recursion','import helper\nprint(helper.rec(5))',{files:[helper]}],['error','import helper\nhelper.fail()',{files:[{name:'helper.py',content:'def fail():\n    return missing'}]}],['syntax','import helper',{files:[{name:'helper.py',content:'def broken('}]}],['allowed','import helper\nprint(helper.value)',{files:[{name:'helper.py',content:'import math\nimport random\nfrom datetime import date\nvalue=math.sqrt(9)'}]}],['vfs','import helper\nprint(helper.value)',{files:[{name:'helper.py',content:'with open("module.txt","w") as f:\n    f.write("가")\nvalue=3'}]}],['not-start-snapshot','with open("newmodule.py","w") as f:\n    f.write("value=3")\nimport newmodule\nprint(newmodule.value)',intentional('실행 시작 시점의 명시적 저장 모듈 스냅샷만 사용')],['relative','from . import helper',unsupported('상대 import')],['wildcard','from math import *\nprint(pi)',unsupported('와일드카드 import')],['dynamic','print(__import__("math").pi)',unsupported('동적 import')]]);
const mathRows={sqrt:['9','0','-1','float("inf")','"x"'],ceil:['1.2','-1.2','float("inf")'],floor:['1.2','-1.2','float("nan")'],trunc:['-1.2','float("inf")'],fabs:['-2','-0.0'],factorial:['0','5','18','19','-1','2.0'],gcd:['12,18','0,0','-12,18','1.0,2'],pow:['2,3','0,-1','-2,0.5'],sin:['0','1','float("inf")'],cos:['0','1'],tan:['0','1'],radians:['180','-90'],degrees:['3.141592653589793','0'],log:['1','8,2','0','-1','8,1'],log10:['100','0'],exp:['0','1','1000'],isfinite:['1','float("inf")'],isinf:['float("inf")','1'],isnan:['float("nan")','1']};
for (const [fn,args] of Object.entries(mathRows)) { for (const [i,arg] of args.entries()) add('math',`${fn}-${i}`,`import math\nprint(math.${fn}(${arg}))`,{numeric:true,...(fn==='factorial'&&arg==='19'?intentional('math.factorial 18 상한'): {})}); add('math',`${fn}-arity`,`import math\nmath.${fn}()`); }
for (const name of ['pi','e','tau','inf','nan']) add('math',`constant-${name}`,`import math\nprint(math.${name})`,{numeric:true});
scripts('standard', [['random-sequence','import random\nrandom.seed(123)\nprint([random.randint(1,100) for x in range(5)])',intentional('Mulberry32와 CPython MT19937 난수열 차이')],['random-repeat','import random\nrandom.seed(7)\na=[random.randint(1,9) for x in range(5)]\nrandom.seed(7)\nb=[random.randint(1,9) for x in range(5)]\nprint(a==b)'],['random-range','import random\nrandom.seed(7)\nprint(all(2<=random.randint(2,4)<=4 for x in []))',unsupported('제너레이터 표현식')],['random-range-list','import random\nrandom.seed(7)\nprint(all([2<=random.randint(2,4)<=4 for x in range(20)]))'],['random-sample','import random\nprint(sorted(random.sample([1,2,3],3)))'],['random-choice','import random\nprint(random.choice([7]))'],['random-empty','import random\nrandom.choice([])'],['random-invalid','import random\nrandom.randint(2,1)'],['random-step','import random\nrandom.seed(1)\nprint(all([random.randrange(0,10,2)%2==0 for x in range(10)]))'],['date-normal','from datetime import date\nprint(date(2026,9,15))'],['date-leap','from datetime import date\nprint(date(2024,2,29))'],['date-invalid','from datetime import date\nprint(date(2023,2,29))'],['date-order','from datetime import date\nprint(date(2024,1,1)<date(2025,1,1))'],['date-min','from datetime import date\nprint(date(1,1,1))'],['date-year-zero','from datetime import date\nprint(date(0,1,1))'],['date-max','from datetime import date\nprint(date(9999,12,31))'],['date-today','from datetime import date\nprint(date.today())',{notes:'실행 당시 현지 날짜 비교; 시간대와 실행 시각은 환경에 기록'}],['date-fixed','from datetime import date\nprint(date.today())',{fixedClock:'2024-02-29T03:00:00Z',...intentional('VMOptions 고정 시계 주입 2024-02-29; CPython은 실제 현지 날짜')}]]);
const txt={name:'data.txt',content:'가,1\r\n나,2\n'};
scripts('file-output', [['read','with open("data.txt") as f:\n    print(f.read())',{files:[txt]}],['readline','with open("data.txt") as f:\n    print(f.readline(),end="")',{files:[txt]}],['readlines','with open("data.txt") as f:\n    print(f.readlines())',{files:[txt]}],['write','with open("a.txt","w") as f:\n    print(f.write("가😀"))'],['append','with open("data.txt","a") as f:\n    f.write("다,3")\nwith open("data.txt") as f:\n    print(f.read())',{files:[txt]}],['close','f=open("data.txt")\nf.close()\nprint(f.closed)',{files:[txt]}],['closed-access','f=open("data.txt")\nf.close()\nf.read()',{files:[txt]}],['iterate','with open("data.txt") as f:\n    for line in f:\n        print(line.strip())',{files:[txt]}],['missing','open("missing.txt")'],['exception-write','try:\n    with open("a.txt","w") as f:\n        f.write("x")\n        raise ValueError("x")\nexcept ValueError:\n    pass\nwith open("a.txt") as f:\n    print(f.read())'],['euckr','with open("data.csv",encoding="euc-kr") as f:\n    print(f.read())',{files:[{name:'data.csv',content:'이름,점수\n민수,90\n',encoding:'euc-kr'}]}],['euckr-write','with open("a.txt","w",encoding="euc-kr") as f:\n    f.write("가")',intentional('EUC-KR 쓰기 미지원')],['path','open("subdirectory/data.txt")',intentional('평면 VFS, 외부 경로 및 폴더 접근 차단')],['empty-program','x=10'],['empty-print','print("")'],['print-sep','print(1,2,sep="-",end="!")'],['print-none-sep','print(1,2,sep=None)'],['print-values','print(None,True,False,1.0)'],['nested-float','print([1.0,(-0.0,),{"x":2.0}])'],['f-expression','x=2\nprint(f"값:{x+1}")'],['f-braces','print(f"{{hello}}")'],['f-left','print(f"{\'가\':<5}")'],['f-right','print(f"{\'가\':>5}")'],['f-center','print(f"{\'가\':^5}")'],['f-zero','print(f"{123:05}")'],['f-precision','print(f"{3.14159:.2f}")'],['f-unsupported','print(f"{255:x}")',unsupported('문서화된 형식 지정 범위 밖 x')],['f-default','print(f"{1.0}")'],['input','name=input("이름:")\nprint(name)',{input:['민수']}],['read-count','with open("data.txt") as f:\n    print(f.read(1),f.read(2))',{files:[txt]}],['write-read-mode','with open("data.txt") as f:\n    f.write("x")',{files:[txt]}],['read-write-mode','with open("a.txt","w") as f:\n    f.read()']]);
for(const n of [9999,10000,10001,10002]) { add('safety',`collection-${n}`,`print(len(list(range(${n}))))`,intentional('독립 컬렉션/반복 물질화 상한 검사')); add('safety',`loop-${n}`,`n=0\nfor x in range(${n}):\n    n+=1\nprint(n)`,intentional('VM 누적 반복 제한 10000')); }
scripts('safety', [['output-before','print("x"*99999)',intentional('출력 상한 100000 UTF-16 코드 단위')],['output-after','try:\n    print("x"*100000)\nexcept:\n    print("caught")',intentional('출력 제한은 bare except로 잡을 수 없음')],['instructions','try:\n    while True:\n        pass\nexcept:\n    print("caught")',{vmOnly:'CPython 무한 루프는 실행하지 않음',...intentional('명령/반복 실행 제한')}],['files-count','for n in range(101):\n    with open(f"f{n}.txt","w") as f:\n        f.write("x")',intentional('VFS 파일 수 100 제한')],['file-size','with open("a.txt","w") as f:\n    for n in range(12):\n        f.write("x"*100000)',intentional('VFS 파일당 크기 제한')],['turtle-limit','import turtle\nt=turtle.Turtle()\nfor n in range(6000):\n    t.forward(1)',{vmOnly:'CPython GUI turtle는 headless oracle에서 실행하지 않음',...intentional('브라우저 turtle 명령 제한')}],['turtle-normal','import turtle\nt=turtle.Turtle()\nt.forward(80)\nturtle.done()',{vmOnly:'브라우저 Canvas와 CPython Tk GUI는 별도 실검증',...intentional('브라우저 turtle 그래픽')}]]);
// Reviewed against current README and existing tests; these are not bug fixes.
Object.assign(cases.find(c=>c.id==='string-operation-48'),intentional('README의 드문 Unicode 대소문자/title 차이. CPython Unicode 15.0과 Node Unicode 버전 및 titlecase/uppercase 차이'));
Object.assign(cases.find(c=>c.id==='assignment-nested-partial'),intentional('기존 core-v2-functions.test.ts가 의도적으로 보장한 전체 대상 사전 검증/부분 저장 방지. CPython의 단계별 중첩 언패킹과 다름'));
Object.assign(cases.find(c=>c.id==='function-keyword-only'),unsupported('bare * 키워드 전용 매개변수는 명시된 *args/**kwargs 범위와 별개이며 미구현'));
Object.assign(cases.find(c=>c.id==='builtin-range-repr'),{policy:'educational-compatible',notes:'기본 step=1을 생략하지 않는 표현 차이; 동일한 range 값'});
for(const n of [991,992,993,994,995,996,997,998,999])add('function',`depth-${n}`,`def f(n):\n    return 0 if n==0 else f(n-1)+1\nprint(f(${n}))`,intentional('CPython oracle 실행 프레임을 포함한 실제 재귀 실패 경계 측정'));
exprs('numeric',[
 ['negative-boundary-match','-9007199254740992',intentional('문서화된 안전 정수 범위 밖')],['negative-boundary-fail','-9007199254740993',intentional('문서화된 안전 정수 범위 밖')],
 ['float-floor-before','1.0//0.5',{numeric:true}],['float-floor-edge','1.0//0.2',{numeric:true}],['float-floor-near','0.3//0.1',{numeric:true}],['float-modulo-edge','1.0%0.1',{numeric:true}],['float-underflow','1e-324',{numeric:true}],['float-subnormal','5e-324',{numeric:true}],['float-near-one','1.0000000000000002',{numeric:true}],['complex-power','(-1)**0.5',unsupported('복소수는 교육용 수치 범위 밖')],
]);
exprs('string',[['repr-newline','["a\\nb"]'],['repr-tab','["a\\tb"]'],['repr-backslash','["a\\\\b"]'],['repr-quotes','["it\'s"]'],['unicode-titlecase','"ǅabc".capitalize()',intentional('README의 드문 Unicode titlecase 차이')],['unicode-numeric','"½".isalnum()'],['unicode-digit','"①".isdigit()',intentional('README의 드문 Unicode 판별 차이')]]);
scripts('evaluation',[
 ['simple-subscript-assign',mark+'a=[0]\na[mark("index",0)]=mark("rhs",5)\nprint(a,events)'],
 ['simple-subscript-chain',mark+'a=[0,0]\na[mark("first",0)]=a[mark("second",1)]=mark("rhs",7)\nprint(a,events)'],
 ['simple-subscript-aug',mark+'a=[[1]]\na[mark("i",0)][mark("j",0)]+=mark("rhs",2)\nprint(a,events)'],
]);
scripts('file-output',[
 ['read-emoji','with open("unicode.txt") as f:\n    print(f.read(1))\n    print(f.read(1))',{files:[{name:'unicode.txt',content:'😀가'}]}],
 ['readlines-lf','with open("lf.txt") as f:\n    print(f.readlines())',{files:[{name:'lf.txt',content:'a\nb\n'}]}],
 ['read-lf','with open("lf.txt") as f:\n    print(f.read(),end="")',{files:[{name:'lf.txt',content:'a\nb\n'}]}],
]);
scripts('safety',[
 ['repeat-10000','print(len([0]*10000))',intentional('컬렉션 곱셈 경로 상한')],['repeat-10001','print(len([0]*10001))',intentional('컬렉션 곱셈 경로 상한')],
 ['instructions-finite','x=0\ntry:\n    for n in range(9999):\n'+Array(200).fill('        x+=1').join('\n')+'\nexcept:\n    print("caught")\nprint(x)',intentional('CPython도 유한 실행. VM 명령 1,000,000 상한이 반복 상한보다 먼저 적용되는지 검사')],
]);
Object.assign(cases.find(c=>c.id==='string-repr-quotes'),{policy:'educational-compatible',notes:'따옴표 선택과 동등한 이스케이프 표현 차이; 내용은 동일'});
export const duplicateAliases = {'exception-finally-replace':'legacy-16','exception-reraise-outside':'legacy-17','builtin-call-13':'numeric-operation-19','exception-zero':'numeric-operation-37','collection-set-equal':'comparison-value-11','collection-set-subset':'comparison-value-17','file-output-empty-print':'string-operation-0'};
for(let i=cases.length-1;i>=0;i--)if(duplicateAliases[cases[i].id])cases.splice(i,1);
// 0.0 and 1e-324 have the same CPython AST value, but deliberately test distinct lexer/underflow paths.
add('exception','finally-inner-catch-preserves-return','def f():\n    try:\n        return 1\n    finally:\n        try:\n            raise ValueError("x")\n        except ValueError:\n            pass\nprint(f())');
for(const id of ['assignment-slice-assign','assignment-step-assign','assignment-step-size'])Object.assign(cases.find(c=>c.id===id),unsupported('원래 Core v2 슬라이싱 절은 start:stop:step 조회 확장이며 슬라이스 대입은 약속하지 않음. 현재 읽기/삭제와 달리 쓰기 미구현'));
cases.find(c=>c.id==='builtin-call-37').notes='iter/next는 Core v2 명시적 내장 함수 목록 밖이며 StopIteration 연결도 미지원';
const ids=new Set(); for(const c of cases) { if(ids.has(c.id))throw Error(`Duplicate ${c.id}`);ids.add(c.id); }
