import { describe, expect, it } from "vitest";
import { compile } from "../compiler/compiler";
import { CompilerError } from "../compiler/token";
import { VM, type VMEvent } from "./vm";
const run=(code:string)=>{const events:VMEvent[]=[];const vm=new VM(compile(code),event=>events.push(event));vm.execute();return events.filter((event):event is Extract<VMEvent,{type:"output"}>=>(event.type==="output")).map(event=>event.text).join("");};
const error=(code:string)=>{const events:VMEvent[]=[];new VM(compile(code),event=>events.push(event)).execute();return events.at(-1) as Extract<VMEvent,{type:"error"}>;};
describe("5단계 클래스",()=>{
 it("클래스 속성, 생성자, 속성 변경과 메서드를 처리한다",()=>expect(run('class Book:\n    category = "도서"\n    def __init__(self, title, year):\n        self.title = title\n        self.year = year\n    def age(self, now=2026):\n        return now - self.year\nbook = Book("데미안", 1919)\nprint(book.title)\nprint(book.age())\nprint(book.category)')).toBe("데미안\n107\n도서\n"));
 it("결합 메서드와 객체 참조를 처리한다",()=>expect(run('class Box:\n    def __init__(self):\n        self.values = []\n    def add(self, value):\n        self.values.append(value)\nfirst = Box()\nsecond = first\nmethod = second.add\nmethod(10)\nprint(first.values)')).toBe("[10]\n"));
 it("__str__과 클래스 속성 가리기를 처리한다",()=>expect(run('class Book:\n    school = "한국"\n    def __init__(self, title):\n        self.title = title\n    def __str__(self):\n        return self.title\nfirst = Book("소나기")\nsecond = Book("데미안")\nfirst.school = "정보"\nprint(first)\nprint(str(first))\nprint(f"도서: {second}")\nprint(first.school)\nprint(second.school)')).toBe("소나기\n소나기\n도서: 데미안\n정보\n한국\n"));
 it("클래스 속성 수정과 직접 메서드 호출을 처리한다",()=>expect(run('class Student:\n    school = "한국고"\nclass Calculator:\n    def double(self, value):\n        return value * 2\nfirst = Student()\nsecond = Student()\nfirst.school = "정보고"\nStudent.school = "새로운학교"\ncalculator = Calculator()\nmethod = calculator.double\nprint(first.school)\nprint(second.school)\nprint(method(10))\nprint(Calculator.double(calculator, 20))')).toBe("정보고\n새로운학교\n20\n40\n"));
 it("중첩 속성, 메서드 내부 호출과 컬렉션 참조를 처리한다",()=>expect(run('class Box:\n    def __init__(self):\n        self.values = []\nclass Calculator:\n    def double(self, value):\n        return value * 2\n    def quadruple(self, value):\n        return self.double(self.double(value))\nfirst = Box()\nsecond = first\nboxes = [first]\nlookup = {"box": first}\nsecond.values.append(10)\nboxes[0].values.append(20)\nlookup["box"].values.append(30)\nprint(first.values)\nprint(Calculator().quadruple(5))')).toBe("[10, 20, 30]\n20\n"));
 it("생성자 기본값과 키워드 인수를 처리한다",()=>expect(run('class Movie:\n    def __init__(self, title, genre="드라마"):\n        self.title = title\n        self.genre = genre\nmovie = Movie(genre="코미디", title="영화")\nprint(movie.title, movie.genre)')).toBe("영화 코미디\n"));
 it("키워드 생성자 인수 뒤의 마지막 쉼표를 처리한다",()=>expect(run('class Movie:\n    def __init__(self, title):\n        self.title = title\nmovie = Movie(\n    title="영화",\n)\nprint(movie.title)')).toBe("영화\n"));
 it("속성·생성자·메서드 오류를 줄 번호와 함께 처리한다",()=>{for(const [code,line] of [['class A:\n    pass\na=A()\nprint(a.none)',4],['class A:\n    pass\nprint(A.none)',3],['value=1\nvalue.x=2',2],['text="x"\ntext.x=2',2],['item=(1,)\nitem.x=2',2],['class A:\n    value=1\na=A()\na.value()',4],['class A:\n    def __init__(self, value):\n        pass\nA()',4],['class A:\n    def __init__(self):\n        pass\nA(1)',4],['class A:\n    def method(self, value):\n        return value\na=A()\na.method()',5],['class A:\n    def method(self):\n        pass\na=A()\na.method(1)',5],['class A:\n    def __init__(self):\n        return 1\nA()',4],['class A:\n    def __str__(self):\n        return 1\nprint(A())',4]] as [string,number][]){const result=error(code);expect(result.type).toBe("error");expect(result.error.line).toBe(line);expect(result.error.message).not.toMatch(/Error|stack|undefined/);}});
 it("상속·생성자 중복 인수·클래스 밖 self를 오류 처리한다",()=>{try{compile('class Child(Base):\n    pass');}catch(cause){expect(cause).toBeInstanceOf(CompilerError);expect((cause as CompilerError).detail.line).toBe(1);}for(const [code,line] of [['class A:\n    def __init__(self, value):\n        pass\nA(1, value=2)',4],['class A:\n    def __init__(self):\n        pass\nA(other=1)',4],['class A:\n    def method(self, value):\n        return value\nA.method(1)',4],['print(self)',1]] as [string,number][]){const result=error(code);expect(result.type).toBe("error");expect(result.error.line).toBe(line);expect(result.error.message).not.toMatch(/Error|stack|undefined/);}});
});
