import { describe, expect, it } from "vitest";
import { compile } from "../compiler/compiler";
import { VM, type VMEvent } from "./vm";
const start = (code: string) => { const events: VMEvent[] = [], vm = new VM(compile(code), e => events.push(e)); vm.execute(); return { vm, events }; };
const output = (events: VMEvent[]) => events.filter(e => e.type === "output").map(e => e.text).join("");
const prints = (code: string, expected: string) => { const { events } = start(code); expect(events.at(-1)).toEqual({ type: "complete" }); expect(output(events)).toBe(expected); };
describe("Core v2 raise/finally 공통 제어 이동", () => {
  it("명시적 ValueError 생성과 발생", () => prints('try:\n    raise ValueError("잘못된 값")\nexcept ValueError as error:\n    print(str(error))', "잘못된 값\n"));
  it("오류 객체를 변수에 보관해 발생", () => prints('error = TypeError("설명")\ntry:\n    raise error\nexcept TypeError as caught:\n    print(str(caught))', "설명\n"));
  it("오류 클래스 직접 raise", () => prints('try:\n    raise ValueError\nexcept ValueError:\n    print("처리")', "처리\n"));
  it("잘못된 raise 값은 해당 줄의 TypeError", () => expect(start('a = 1\nraise a').events.at(-1)).toMatchObject({ type: "error", error: { line: 2, pythonType: "TypeError" } }));
  it("활성 예외 없는 bare raise", () => expect(start('raise').events.at(-1)).toMatchObject({ type: "error", error: { line: 1, pythonType: "RuntimeError", message: "다시 발생시킬 오류가 없습니다." } }));
  it("bare raise는 원본 오류 위치를 유지", () => expect(start('try:\n    print(1 / 0)\nexcept ZeroDivisionError:\n    raise').events.at(-1)).toMatchObject({ type: "error", error: { line: 2, pythonType: "ZeroDivisionError" } }));
  it("finally는 정상 종료에 정확히 한 번 실행", () => prints('try:\n    print("본문")\nfinally:\n    print("정리")\nprint("끝")', "본문\n정리\n끝\n"));
  it("except else finally 순서", () => prints('try:\n    print("본문")\nexcept ValueError:\n    print("실패")\nelse:\n    print("성공")\nfinally:\n    print("정리")', "본문\n성공\n정리\n"));
  it("예외 처리 후 finally", () => prints('try:\n    raise ValueError("x")\nexcept ValueError:\n    print("처리")\nelse:\n    print("실패")\nfinally:\n    print("정리")', "처리\n정리\n"));
  it("처리되지 않은 예외도 finally 이후 전달", () => { const { events } = start('try:\n    raise ValueError("x")\nfinally:\n    print("정리")'); expect(output(events)).toBe("정리\n"); expect(events.at(-1)).toMatchObject({ type: "error", error: { line: 2, pythonType: "ValueError" } }); });
  it("return 값을 먼저 계산하고 finally 실행", () => prints('def f():\n    value = 1\n    try:\n        return value\n    finally:\n        value = 2\n        print("정리")\nprint(f())', "정리\n1\n"));
  it("finally return은 보류 중인 return을 대체", () => prints('def f():\n    try:\n        return 1\n    finally:\n        return 2\nprint(f())', "2\n"));
  it("finally return은 보류 중인 Python 예외를 대체", () => prints('def f():\n    try:\n        raise ValueError("x")\n    finally:\n        return 3\nprint(f())', "3\n"));
  it("break 전에 finally 실행하고 else는 생략", () => prints('for n in range(2):\n    try:\n        break\n    finally:\n        print("정리")\nelse:\n    print("실패")', "정리\n"));
  it("continue마다 finally 실행 후 정상 else", () => prints('for n in range(2):\n    try:\n        continue\n    finally:\n        print(n)\nelse:\n    print("끝")', "0\n1\n끝\n"));
  it("finally 안의 break는 보류 중인 continue를 대체", () => prints('for n in range(3):\n    try:\n        continue\n    finally:\n        break\nelse:\n    print("실패")\nprint("끝")', "끝\n"));
  it("finally 내부 반복문 continue는 보류 return을 유지", () => prints('def f():\n    try:\n        return 7\n    finally:\n        for n in range(2):\n            continue\n        print("정리")\nprint(f())', "정리\n7\n"));
  it("중첩 finally는 안쪽부터 실행", () => prints('def f():\n    try:\n        try:\n            return 1\n        finally:\n            print("안")\n    finally:\n        print("밖")\nprint(f())', "안\n밖\n1\n"));
  it("finally의 새 예외가 이전 예외를 대체", () => expect(start('try:\n    raise ValueError("이전")\nfinally:\n    raise TypeError("새 오류")').events.at(-1)).toMatchObject({ type: "error", error: { line: 4, pythonType: "TypeError", message: "새 오류" } }));
  it("except에서 다시 raise 후 finally", () => prints('try:\n    try:\n        raise ValueError("x")\n    except ValueError:\n        raise\n    finally:\n        print("정리")\nexcept ValueError:\n    print("밖")', "정리\n밖\n"));
  it("finally에서 bare raise는 보류 예외를 사용", () => expect(start('try:\n    raise ValueError("x")\nfinally:\n    raise').events.at(-1)).toMatchObject({ type: "error", error: { line: 2, pythonType: "ValueError" } }));
  it("except 내부 finally는 오류 변수를 정리 전에 읽는다", () => prints('def f():\n    try:\n        raise ValueError("유지")\n    except ValueError as error:\n        try:\n            return 1\n        finally:\n            print(str(error))\nprint(f())', "유지\n1\n"));
  it("try의 finally 전에 except 변수 제거", () => prints('try:\n    raise ValueError("x")\nexcept ValueError as error:\n    pass\nfinally:\n    try:\n        print(error)\n    except NameError:\n        print("제거")', "제거\n"));
  it("try를 빠져나간 break의 handler는 후속 오류를 잡지 않는다", () => { const { events } = start('for n in range(1):\n    try:\n        break\n    except ValueError:\n        print("실패")\nraise ValueError("끝")'); expect(output(events)).toBe(""); expect(events.at(-1)).toMatchObject({ type: "error", error: { line: 6, message: "끝" } }); });
  it("finally 중 input은 보류 return을 유지", () => { const { vm, events } = start('def f():\n    try:\n        return 8\n    finally:\n        print(input("정리: "))\nprint(f())'); expect(events.at(-1)).toEqual({ type: "input", prompt: "정리: " }); vm.resume("확인"); expect(output(events)).toBe("확인\n8\n"); expect(events.at(-1)).toEqual({ type: "complete" }); });
  it("with 내부에서 처리한 예외는 파일을 조기 닫지 않는다", () => prints('with open("test.txt", "w") as file:\n    try:\n        raise ValueError("x")\n    except ValueError:\n        print(file.closed)\n    file.write("정상")\nprint(file.closed)', "False\nTrue\n"));
  it("with를 벗어나는 break는 파일을 닫는다", () => prints('for n in range(1):\n    with open("test.txt", "w") as file:\n        file.write("저장")\n        break\nprint(file.closed)', "True\n"));
  it("중단 신호는 except나 finally의 return으로 무력화 불가", () => { const { events } = start('def f():\n    try:\n        print("x" * 100000)\n    except:\n        print("우회")\n    finally:\n        return 1\nprint(f())'); expect(output(events)).toBe(""); expect(events.at(-1)).toMatchObject({ type: "error", error: { message: "출력량 제한을 초과했습니다." } }); });
  it("사용자 중지 시 내부 파일 정리만 하고 학생 finally는 실행하지 않는다", () => { const { vm, events } = start('with open("test.txt", "w") as file:\n    try:\n        file.write("저장")\n        input()\n    finally:\n        print("학생 정리")'); vm.stop(); expect(output(events)).toBe(""); expect(events.at(-1)).toEqual({ type: "stopped" }); expect(events).toContainEqual({ type: "file-change", name: "test.txt", content: "저장" }); });
});
