import type { Bytecode, Instruction } from "../compiler/opcode";
import type { StudentError } from "../compiler/token";
import { BuiltinModules, ModuleError, type ModuleOptions } from "./modules";
import { GraphicsLimitError, TurtleError, type TurtleGraphicsCommand } from "./turtle";
import { isDate, isModule, equal, isBoundMethod, isBuiltin, isClass, isDict, isException, isFile, isFunction, isInstance, isIterator, isList, isMap, isRange, isSlice, isTuple, isTurtle, isTurtleMethod, keyOK, printable, repr, truthy, typeName, type ClassValue, type FileValue, type FunctionValue, type IteratorValue, type Value } from "./value";

export type VMEvent = { type: "output"; text: string } | { type: "input"; prompt: string } | { type: "file-change"; name: string; content: string } | { type: "graphics"; commands: TurtleGraphicsCommand[] } | { type: "complete" } | { type: "error"; error: StudentError } | { type: "stopped" };
export interface VMOptions extends ModuleOptions { fileEncodings?: ReadonlyMap<string, "utf-8" | "euc-kr">; }
const MAX_OUTPUT = 100_000, MAX_ITERATIONS = 10_000, ASYNC_BATCH = 400, GRAPHICS_BATCH = 48;
const BUILTINS = new Set(["int", "float", "str", "bool", "len", "list", "tuple", "dict", "sum", "min", "max", "map", "input", "print", "range", "type", "open"]);
const ERROR_TYPES = new Set(["ImportError", "Exception", "NameError", "TypeError", "ValueError", "ZeroDivisionError", "IndexError", "KeyError", "AttributeError", "FileNotFoundError", "RuntimeError"]);
type Frame = { bytecode: Bytecode; pc: number; stack: Value[]; env: Map<string, Value>; outerEnvs: Map<string, Value>[]; localNames: Set<string>; globalNames: Set<string>; functionName?: string; classValue?: ClassValue };
type Handler = { bytecode: Bytecode; depth: number; stack: Value[]; env: Map<string, Value>; localNames: Set<string>; globalNames: Set<string>; handlers: { type?: string; name?: string; target: number }[] };
export class VM {
  private pc = 0; private stack: Value[] = []; private globals = new Map<string, Value>([["__name__", "__main__"]]); private env = this.globals; private outerEnvs: Map<string, Value>[] = []; private localNames = new Set<string>(); private globalNames = new Set<string>(); private frames: Frame[] = []; private activeFunctions: string[] = []; private pendingInstances: { depth: number; instance: Extract<Value,{kind:"instance"}>; instruction: Instruction }[] = []; private withFiles: { file: FileValue; depth: number }[] = []; private exceptionHandlers: Handler[] = []; private exceptionBindings: { env: Map<string, Value>; name: string; depth: number }[] = []; private waiting = false; private stopped = false; private finished = false; private asyncMode = false; private outputSize = 0; private iterations = 0; private graphics: TurtleGraphicsCommand[] = [];
  private readonly modules: BuiltinModules;
  constructor(private bytecode: Bytecode, private readonly notify: (event: VMEvent) => void, private readonly files = new Map<string, string>(), private readonly options: VMOptions = {}) { this.modules = new BuiltinModules({ ...options, emitGraphics: command => this.graphicsCommand(command) }); }
  private graphicsCommand(command: TurtleGraphicsCommand): void { this.graphics.push(command); if (this.graphics.length >= GRAPHICS_BATCH || command.type === "finish") this.flushGraphics(); }
  private flushGraphics(): void { if (this.graphics.length) { this.notify({ type: "graphics", commands: this.graphics }); this.graphics = []; } }
  private library<T>(i: Instruction, action: () => T): T { try { return action(); } catch (error) { if (error instanceof GraphicsLimitError) return this.systemFail(i, error.message); if (error instanceof TurtleError) throw new VMFailure({ line: i.line, column: i.column, category: error.pythonType === "TypeError" ? "type" : error.pythonType === "AttributeError" ? "name" : "value", message: error.message }, error.pythonType); if (!(error instanceof ModuleError)) throw error; throw new VMFailure({ line: i.line, column: i.column, category: error.pythonType === "TypeError" ? "type" : error.pythonType === "ImportError" || error.pythonType === "AttributeError" ? "name" : "value", message: error.message }, error.pythonType); } }
  stop(): void { if (this.finished || this.stopped) return; this.closeAll(); this.clearBindings(); this.stopped = true; this.waiting = false; this.finished = true; this.flushGraphics(); this.notify({ type: "stopped" }); }
  resume(input: string): void { if (!this.waiting || this.stopped || this.finished) return; this.waiting = false; this.stack.push(input); this.asyncMode ? this.executeAsync() : this.execute(); }
  execute(): void { this.asyncMode = false; this.run(Number.POSITIVE_INFINITY); }
  executeAsync(): void { this.asyncMode = true; this.run(ASYNC_BATCH); }
  private run(budget: number): void {
    try { let count = 0; while (!this.waiting && !this.stopped && !this.finished && this.pc < this.bytecode.instructions.length && count++ < budget) this.step(this.bytecode.instructions[this.pc++]); if (!this.waiting && !this.stopped && !this.finished && this.pc >= this.bytecode.instructions.length) { if (this.frames.at(-1)?.classValue) { this.finishClass(); this.run(budget); return; } this.finished = true; this.flushGraphics(); this.notify({ type: "complete" }); } else if (!this.waiting && !this.stopped && !this.finished && this.asyncMode) setTimeout(() => this.run(ASYNC_BATCH), 0); }
    catch (reason) { if (reason instanceof VMFailure && reason.catchable && this.handle(reason)) { this.run(budget); return; } this.closeAll(); this.clearBindings(); this.finished = true; this.flushGraphics(); if (reason instanceof VMFailure) this.notify({ type: "error", error: reason.error }); else this.notify({ type: "error", error: { line: 1, column: 1, category: "runtime", message: "실행 중 오류가 발생했습니다." } }); }
  }
  private fail(instruction: Instruction, category: StudentError["category"], message: string): never { const type = category === "name" ? (message.includes("파일을 찾") ? "FileNotFoundError" : message.includes("속성") ? "AttributeError" : "NameError") : category === "type" ? "TypeError" : category === "value" ? (message.includes("0으로 나") ? "ZeroDivisionError" : message.includes("키가 없") ? "KeyError" : message.includes("위치") || message.includes("인덱스") ? "IndexError" : "ValueError") : "RuntimeError"; throw new VMFailure({ line: instruction.line, column: instruction.column, category, message }, type); }
  private systemFail(instruction: Instruction, message: string): never { throw new VMFailure({ line: instruction.line, column: instruction.column, category: "runtime", message }, "RuntimeError", false); }
  private clearBindings(depth = -1): void { this.exceptionBindings = this.exceptionBindings.filter(binding => { if (binding.depth >= depth) { binding.env.delete(binding.name); return false; } return true; }); }
  private handle(failure: VMFailure): boolean { for (let index = this.exceptionHandlers.length - 1; index >= 0; index--) { const region = this.exceptionHandlers[index], match = region.handlers.find(handler => !handler.type || handler.type === "Exception" || handler.type === failure.type); if (!match) continue; while (this.frames.length > region.depth) { this.frames.pop(); this.activeFunctions.pop(); } this.withFiles = this.withFiles.filter(item => { if (item.depth >= region.depth) { this.close(item.file); return false; } return true; }); this.exceptionHandlers.splice(index, 1); this.bytecode = region.bytecode; this.pc = match.target; this.stack = region.stack; this.env = region.env; this.localNames = region.localNames; this.globalNames = region.globalNames; if (match.name) { this.env.set(match.name, { kind: "exception", name: failure.type, message: failure.error.message, line: failure.error.line, column: failure.error.column }); this.exceptionBindings.push({ env: this.env, name: match.name, depth: region.depth }); } return true; } return false; }
  private pop(instruction: Instruction): Value { const value = this.stack.pop(); if (value === undefined) return this.fail(instruction, "runtime", "계산 중 오류가 발생했습니다."); return value; }
  private loadName(instruction: Instruction, name: string): Value { if (this.globalNames.has(name)) { if (this.globals.has(name)) return this.globals.get(name)!; } else if (this.localNames.has(name)) { if (this.env.has(name)) return this.env.get(name)!; return this.fail(instruction, "name", `지역 변수 '${name}'에 아직 값이 없습니다.`); } else if (this.env.has(name)) return this.env.get(name)!; for (const outer of this.outerEnvs) if (outer.has(name)) return outer.get(name)!; if (this.globals.has(name)) return this.globals.get(name)!; if (ERROR_TYPES.has(name)) return { kind: "error-type", name }; if (BUILTINS.has(name)) return { kind: "builtin", name }; return this.fail(instruction, "name", `'${name}' 변수가 정의되지 않았습니다.`); }
  private storeName(name: string, value: Value): void { (this.globalNames.has(name) ? this.globals : this.env).set(name, value); }
  private finishClass(): void { const frame = this.frames.pop()!; const value = frame.classValue!; this.bytecode = frame.bytecode; this.pc = frame.pc; this.stack = frame.stack; this.env = frame.env; this.outerEnvs = frame.outerEnvs; this.localNames = frame.localNames; this.globalNames = frame.globalNames; this.stack.push(value); }
  private attribute(i: Instruction, object: Value, name: string): Value { if (isModule(object)) { const value = object.attributes.get(name); if (value === undefined) return this.fail(i, "name", `${object.name}에 '${name}' 속성이 없습니다.`); return value; } if (isBuiltin(object) && object.name === "datetime.date") return this.library(i, () => this.modules.dateAttribute(name)); if (isTurtle(object)) return this.library(i, () => this.modules.turtleAttribute(object, name)); if (isDate(object)) { if (name === "year" || name === "month" || name === "day") return object[name]; return this.fail(i, "name", `date에 '${name}' 속성이 없습니다.`); } if (isFile(object)) { if (name === "closed") return object.closed; this.fail(i, "name", `파일에 '${name}' 속성이 없습니다.`); } if (isInstance(object)) { if (object.attributes.has(name)) return object.attributes.get(name)!; const value = object.classValue.attributes.get(name); if (value === undefined) this.fail(i, "name", `${object.classValue.name} 객체에 '${name}' 속성이 없습니다.`); return isFunction(value) ? { kind: "bound-method", functionValue: value, instance: object } : value; } if (isClass(object)) { const value = object.attributes.get(name); if (value === undefined) this.fail(i, "name", `${object.name} 클래스에 '${name}' 속성이 없습니다.`); return value; } this.fail(i, "type", "이 값에는 속성이 없습니다."); }
  private setAttribute(i: Instruction, object: Value, name: string, value: Value): void { if (isModule(object) || isDate(object) || isBuiltin(object) || isTurtle(object)) return this.fail(i, "name", "이 속성은 수정할 수 없습니다."); if (isInstance(object)) { object.attributes.set(name, value); return; } if (isClass(object)) { object.attributes.set(name, value); return; } this.fail(i, "type", "이 값에는 속성을 저장할 수 없습니다."); }
  private close(file: FileValue): void { if (file.closed) return; file.closed = true; if (file.dirty) this.notify({ type: "file-change", name: file.name, content: file.content }); }
  private closeAll(): void { this.withFiles.splice(0).forEach(item => this.close(item.file)); }
  private fileLines(file: FileValue): string[] { const rest = file.content.slice(file.position); file.position = file.content.length; return rest.match(/[^\n]*\n|[^\n]+/g) ?? []; }
  private fileLine(file: FileValue): string { const end = file.content.indexOf("\n", file.position); const line = file.content.slice(file.position, end < 0 ? undefined : end + 1); file.position += line.length; return line; }
  private fileRead(i: Instruction, file: FileValue, size?: Value): string { if (file.closed) return this.fail(i, "value", "닫힌 파일은 사용할 수 없습니다."); if (file.mode !== "r") return this.fail(i, "type", "쓰기 모드로 연 파일에서는 읽을 수 없습니다."); if (size !== undefined && (typeof size !== "number" || !Number.isInteger(size) || size < 0)) return this.fail(i, "type", "read() 크기는 0 이상의 정수여야 합니다."); const result = file.content.slice(file.position, size === undefined ? undefined : file.position + size); file.position += result.length; return result; }
  private fileWrite(i: Instruction, file: FileValue, text: Value): number { if (file.closed) return this.fail(i, "value", "닫힌 파일은 사용할 수 없습니다."); if (file.mode === "r") return this.fail(i, "type", "읽기 모드로 연 파일에는 쓸 수 없습니다."); if (typeof text !== "string") return this.fail(i, "type", "write()에는 문자열이 필요합니다."); const next = file.content.slice(0, file.position) + text + file.content.slice(file.position); if (new TextEncoder().encode(next).length > 1_000_000) return this.fail(i, "runtime", "파일 하나는 1MB를 넘을 수 없습니다."); const total = [...this.files.entries()].reduce((sum, [name, content]) => sum + new TextEncoder().encode(name === file.name ? next : content).length, 0); if (total > 10_000_000) return this.fail(i, "runtime", "전체 파일 용량은 10MB를 넘을 수 없습니다."); file.content = next; file.position += text.length; file.dirty = true; this.files.set(file.name, next); return text.length; }
  private openFile(i: Instruction, args: Value[], keywords: Record<string, Value>): void { const allowed = new Set(["mode", "encoding"]); if (Object.keys(keywords).some(name => !allowed.has(name)) || args.length < 1 || args.length > 2) return this.fail(i, "type", "open() 인수가 올바르지 않습니다."); const name = args[0]; const mode = args[1] ?? keywords.mode ?? "r", encoding = keywords.encoding; if (args.length === 2 && keywords.mode !== undefined) return this.fail(i, "type", "mode 인수가 중복되었습니다."); if (typeof name !== "string") return this.fail(i, "type", "파일 이름은 문자열이어야 합니다."); if (!name || name.includes("..") || /[\\/:]/.test(name) || /^[a-zA-Z]:/.test(name) || /^https?:/i.test(name)) return this.fail(i, "value", "앱의 파일 공간 밖에는 접근할 수 없습니다."); if (typeof mode !== "string" || !["r", "w", "a"].includes(mode)) return this.fail(i, "value", "지원하지 않는 파일 모드입니다."); let normalizedEncoding = "utf-8"; if (encoding !== undefined) { if (typeof encoding !== "string") return this.fail(i, "type", "encoding은 문자열이어야 합니다."); const label = encoding.trim().toLowerCase().replaceAll("_", "-"); if (label === "utf8" || label === "utf-8") normalizedEncoding = "utf-8"; else if (label === "euc-kr" || label === "euckr" || label === "cp949") normalizedEncoding = "euc-kr"; else return this.fail(i, "value", `'${encoding}' 인코딩은 현재 지원하지 않습니다.`); } if (normalizedEncoding === "euc-kr" && mode !== "r") return this.fail(i, "value", "EUC-KR은 현재 읽기만 지원합니다. 쓰기는 UTF-8을 사용해 주세요."); const exists = this.files.has(name); const storedEncoding = this.options.fileEncodings?.get(name); if (mode === "r" && exists && storedEncoding && storedEncoding !== normalizedEncoding) return this.fail(i, "value", `이 파일을 ${normalizedEncoding === "euc-kr" ? "EUC-KR" : "UTF-8"}로 읽을 수 없습니다.`); if (mode === "r" && !exists) return this.fail(i, "name", `'${name}' 파일을 찾을 수 없습니다.`); if (!exists && this.files.size >= 100) return this.fail(i, "runtime", "파일은 최대 100개까지 만들 수 있습니다."); const content = mode === "w" ? "" : this.files.get(name) ?? ""; const file: FileValue = { kind: "file", name, mode, content, position: mode === "a" ? content.length : 0, closed: false, dirty: mode !== "r", }; this.files.set(name, content); if (file.dirty) this.notify({ type: "file-change", name, content }); this.stack.push(file); }
  private step(instruction: Instruction): void {
    if (instruction.op === "import_module") { this.stack.push(this.library(instruction, () => this.modules.load(instruction.module, instruction.member))); return; }
    if (instruction.op === "constant") { this.stack.push(instruction.value as Value); return; }
    if (instruction.op === "setup_except") { this.exceptionHandlers.push({ bytecode: this.bytecode, depth: this.frames.length, stack: [...this.stack], env: this.env, localNames: this.localNames, globalNames: this.globalNames, handlers: instruction.handlers }); return; }
    if (instruction.op === "pop_except") { this.exceptionHandlers.pop(); return; }
    if (instruction.op === "clear_exception") { this.env.delete(instruction.name); this.exceptionBindings = this.exceptionBindings.filter(binding => binding.env !== this.env || binding.name !== instruction.name); return; }
    if (instruction.op === "load") { this.stack.push(this.loadName(instruction, instruction.name)); return; }
    if (instruction.op === "dup") { const value = this.stack.at(-1); if (value === undefined) this.fail(instruction, "runtime", "계산 중 오류가 발생했습니다."); this.stack.push(value); return; }
    if (instruction.op === "store") { this.storeName(instruction.name, this.pop(instruction)); return; }
    if (instruction.op === "store_keep") { const value = this.stack.at(-1); if (value === undefined) this.fail(instruction, "runtime", "계산 중 오류가 발생했습니다."); this.storeName(instruction.name, value); return; }
    if (instruction.op === "pop") { this.pop(instruction); return; }
    if (instruction.op === "loop_guard") { if (++this.iterations > MAX_ITERATIONS) this.systemFail(instruction, "실행을 중지했습니다. 반복문이 끝나는 조건을 확인해 주세요."); return; }
    if (instruction.op === "jump") { this.pc = instruction.target; return; }
    if (instruction.op === "jump_if_false") { if (!truthy(this.pop(instruction))) this.pc = instruction.target; return; }
    if (instruction.op === "jump_if_false_keep" || instruction.op === "jump_if_true_keep") { const value = this.stack.at(-1); if (value === undefined) this.fail(instruction, "runtime", "계산 중 오류가 발생했습니다."); const keep = instruction.op === "jump_if_false_keep" ? !truthy(value) : truthy(value); if (keep) this.pc = instruction.target; else this.stack.pop(); return; }
    if (instruction.op === "build_list" || instruction.op === "build_tuple") { const items=this.stack.splice(this.stack.length-instruction.count);this.stack.push({kind:instruction.op==="build_list"?"list":"tuple",items});return; }
    if (instruction.op === "build_dict") { const raw=this.stack.splice(this.stack.length-instruction.count*2),entries:{key:Value;value:Value}[]=[];for(let j=0;j<raw.length;j+=2){if(!keyOK(raw[j]))this.fail(instruction,"type","변경 가능한 값은 딕셔너리 키가 될 수 없습니다.");const old=entries.findIndex(e=>equal(e.key,raw[j]));if(old>=0)entries[old].value=raw[j+1];else entries.push({key:raw[j],value:raw[j+1]});}this.stack.push({kind:"dict",entries});return; }
    if (instruction.op === "build_slice") { const values=this.stack.splice(this.stack.length+0-(Number(instruction.hasStart)+Number(instruction.hasStop)+Number(instruction.hasStep)));const num=(v:Value|undefined)=>v===undefined?undefined:typeof v==="number"&&Number.isInteger(v)?v:this.fail(instruction,"type","슬라이스 위치는 정수여야 합니다.");this.stack.push({kind:"slice",start:num(instruction.hasStart?values.shift():undefined),stop:num(instruction.hasStop?values.shift():undefined),step:num(instruction.hasStep?values.shift():undefined)});return; }
    if (instruction.op === "load_subscript") { const index=this.pop(instruction),object=this.pop(instruction);this.stack.push(this.subscript(instruction,object,index));return; }
    if (instruction.op === "store_subscript") { const value=this.pop(instruction),index=this.pop(instruction),object=this.pop(instruction);this.setSubscript(instruction,object,index,value);return; }
    if (instruction.op === "store_subscript_keep") { const index=this.pop(instruction),object=this.pop(instruction),value=this.stack.at(-1); if(value===undefined)this.fail(instruction,"runtime","계산 중 오류가 발생했습니다."); this.setSubscript(instruction,object,index,value);return; }
    if (instruction.op === "store_attr") { const value=this.pop(instruction),object=this.pop(instruction);this.setAttribute(instruction,object,instruction.name,value);return; }
    if (instruction.op === "store_attr_keep") { const object=this.pop(instruction),value=this.stack.at(-1);if(value===undefined)this.fail(instruction,"runtime","계산 중 오류가 발생했습니다.");this.setAttribute(instruction,object,instruction.name,value);return; }
    if (instruction.op === "load_attr") { this.stack.push(this.attribute(instruction,this.pop(instruction),instruction.name));return; }
    if (instruction.op === "enter_with") { const file = this.pop(instruction); if (!isFile(file)) this.fail(instruction, "type", "with에는 파일 객체가 필요합니다."); this.storeName(instruction.name, file); this.withFiles.push({ file, depth: this.frames.length }); return; }
    if (instruction.op === "exit_with") { const item = this.withFiles.pop(); if (!item) this.fail(instruction, "runtime", "파일 블록을 종료할 수 없습니다."); this.close(item.file); return; }
    if (instruction.op === "call_method") {
      const values = this.stack.splice(this.stack.length - instruction.argc - instruction.keywords.length);
      const args = values.slice(0, instruction.argc), keywords = Object.fromEntries(instruction.keywords.map((name, index) => [name, values[instruction.argc + index]])), object = this.pop(instruction);
      if (isInstance(object) || isClass(object) || isModule(object) || isBuiltin(object) || isDate(object) || isTurtle(object)) this.invoke(instruction, this.attribute(instruction, object, instruction.name), args, keywords);
      else { if (instruction.keywords.length) this.fail(instruction, "type", "이 메서드는 키워드 인수를 지원하지 않습니다."); this.method(instruction, object, instruction.name, args); }
      return;
    }
    if (instruction.op === "make_class") { const classValue:ClassValue={kind:"class",name:instruction.name,attributes:new Map()};this.frames.push({bytecode:this.bytecode,pc:this.pc,stack:this.stack,env:this.env,outerEnvs:this.outerEnvs,localNames:this.localNames,globalNames:this.globalNames,classValue});this.bytecode=instruction.bytecode;this.pc=0;this.stack=[];this.env=classValue.attributes;this.outerEnvs=[];this.localNames=new Set();this.globalNames=new Set();return; }
    if (instruction.op === "make_function") { const defaults = this.stack.splice(this.stack.length - instruction.params.filter(parameter => parameter.hasDefault).length); this.stack.push({ kind: "function", name: instruction.name, params: instruction.params, defaults, localNames: instruction.localNames, globals: instruction.globals, bytecode: instruction.bytecode }); return; }
    if (instruction.op === "run_comprehension") { this.frames.push({ bytecode: this.bytecode, pc: this.pc, stack: this.stack, env: this.env, outerEnvs: this.outerEnvs, localNames: this.localNames, globalNames: this.globalNames }); this.bytecode = instruction.bytecode; this.pc = 0; this.stack = []; this.outerEnvs = [this.env, ...this.outerEnvs]; this.env = new Map(); this.localNames = new Set(instruction.localNames); this.globalNames = new Set(); return; }
    if (instruction.op === "format_value") { const value = this.pop(instruction), raw = this.stringValue(instruction, value); if (instruction.format.kind === "align") { this.stack.push(instruction.format.align === "<" ? raw.padEnd(instruction.format.width) : instruction.format.align === ">" ? raw.padStart(instruction.format.width) : raw.length >= instruction.format.width ? raw : `${" ".repeat(Math.floor((instruction.format.width - raw.length) / 2))}${raw}${" ".repeat(Math.ceil((instruction.format.width - raw.length) / 2))}`); return; } if (instruction.format.kind === "zero") { if (typeof value !== "number" || !Number.isInteger(value)) this.fail(instruction, "type", "0 채움 형식에는 정수가 필요합니다."); const sign = value < 0 ? "-" : "", digits = String(Math.abs(value)); this.stack.push(`${sign}${digits.padStart(Math.max(0, instruction.format.width - sign.length), "0")}`); return; } if (typeof value !== "number") this.fail(instruction, "type", "소수점 형식에는 숫자가 필요합니다."); this.stack.push(value.toFixed(instruction.format.precision)); return; }
    if (instruction.op === "return_value") { this.returnFromFunction(this.pop(instruction)); return; }
    if (instruction.op === "build_string") { const values = this.stack.splice(this.stack.length - instruction.count); this.stack.push(values.map(value => this.stringValue(instruction,value)).join("")); return; }
    if (instruction.op === "unpack") { const value=this.pop(instruction),items=this.items(instruction,value);if(items.length!==instruction.names.length)this.fail(instruction,"value",`${items.length}개의 값을 ${instruction.names.length}개의 변수에 저장할 수 없습니다.`);instruction.names.forEach((name,i)=>this.storeName(name,items[i]));return; }
    if (instruction.op === "iter_prepare") { this.stack.push(this.iterator(instruction, this.pop(instruction))); return; }
    if (instruction.op === "iter_next") { const iterator = this.stack.at(-1); if (!iterator || (!isIterator(iterator) && !isMap(iterator))) this.fail(instruction, "runtime", "반복자를 준비할 수 없습니다."); const value = this.next(instruction, iterator); if (value === undefined) this.pc = instruction.target; else if(instruction.names.length===1)this.storeName(instruction.names[0],value);else {const parts=this.items(instruction,value);if(parts.length!==instruction.names.length)this.fail(instruction,"value",`${parts.length}개의 값을 ${instruction.names.length}개의 변수에 저장할 수 없습니다.`);instruction.names.forEach((n,i)=>this.storeName(n,parts[i]));} return; }
    if (instruction.op === "unary") { const value = this.pop(instruction); if (instruction.operator === "not") { this.stack.push(!truthy(value)); return; } if (typeof value !== "number") this.fail(instruction, "type", "숫자에만 단항 연산을 사용할 수 있습니다."); this.stack.push(instruction.operator === "-" ? -value : value); return; }
    if (instruction.op === "binary") { const right = this.pop(instruction), left = this.pop(instruction); if(instruction.operator==="in"||instruction.operator==="not in"){const found=typeof right==="string"&&typeof left==="string"?right.includes(left):isList(right)||isTuple(right)?right.items.some(x=>equal(x,left)):isDict(right)?right.entries.some(e=>equal(e.key,left)):this.fail(instruction,"type","이 값은 검사할 수 없습니다.");this.stack.push(instruction.operator==="in"?found:!found);}else this.stack.push(this.binary(instruction, left, right)); return; }
    if (instruction.op === "compare") { const values = this.stack.splice(this.stack.length - instruction.count); let matched = true; for (let index = 0; index < instruction.operators.length; index++) { if (!this.compare(instruction, instruction.operators[index], values[index], values[index + 1])) { matched = false; break; } } this.stack.push(matched); return; }
    if (instruction.op === "call") { const values = this.stack.splice(this.stack.length - instruction.argc - instruction.keywords.length); const args = values.slice(0, instruction.argc); const keywords = Object.fromEntries(instruction.keywords.map((name, index) => [name, values[instruction.argc + index]])); this.invoke(instruction, { kind: "builtin", name: instruction.name }, args, keywords); return; }
    if (instruction.op === "call_value") { const values = this.stack.splice(this.stack.length - instruction.argc - instruction.keywords.length); const args = values.slice(0, instruction.argc); const keywords = Object.fromEntries(instruction.keywords.map((name, index) => [name, values[instruction.argc + index]])); const callable = this.pop(instruction); this.invoke(instruction, callable, args, keywords); return; }
  }
  private iterator(i: Instruction, value: Value): IteratorValue | Extract<Value, { kind: "map" }> { if (isIterator(value) || isMap(value)) return value; if (isFile(value)) { if (value.closed) return this.fail(i, "value", "닫힌 파일은 사용할 수 없습니다."); if (value.mode !== "r") return this.fail(i, "type", "쓰기 모드로 연 파일에서는 읽을 수 없습니다."); return { kind: "iterator", values: this.fileLines(value), index: 0 }; } if (typeof value === "string") return { kind: "iterator", values: [...value], index: 0 }; if (isList(value) || isTuple(value)) return { kind: "iterator", values: value.items, index: 0 }; if (isDict(value)) return { kind: "iterator", values: value.entries.map(entry => entry.key), index: 0 }; if (isRange(value)) return { kind: "iterator", values: this.rangeItems(i, value), index: 0 }; return this.fail(i, "type", "이 값은 반복할 수 없습니다."); }
  private rangeItems(i: Instruction, value: Extract<Value, { kind: "range" }>): Value[] { const values: Value[] = []; for (let number = value.start; value.step > 0 ? number < value.stop : number > value.stop; number += value.step) { if (values.length > MAX_ITERATIONS) this.fail(i, "runtime", "반복 횟수 제한을 초과했습니다."); values.push(number); } return values; }
  private next(i: Instruction, value: IteratorValue | Extract<Value, { kind: "map" }>): Value | undefined { if (isIterator(value)) return value.values[value.index++]; const args: Value[] = []; for (const source of value.sources) { const item = this.next(i, source); if (item === undefined) return undefined; args.push(item); } if (isFunction(value.fn)) return this.callFunctionSync(i, value.fn, args); this.invoke(i, value.fn, args, {}); return this.pop(i); }
  private callFunction(i: Instruction, fn: FunctionValue, args: Value[], keywords: Record<string, Value>): void { if (this.activeFunctions.includes(fn.name)) this.fail(i, "runtime", "재귀 함수 호출은 현재 버전에서 지원하지 않습니다."); if (args.length > fn.params.length) this.fail(i, "type", "위치 인수가 너무 많습니다."); const locals = new Map<string, Value>(); const assigned = new Set<string>(); args.forEach((value, index) => { locals.set(fn.params[index].name, value); assigned.add(fn.params[index].name); }); for (const [name, value] of Object.entries(keywords)) { const parameter = fn.params.findIndex(item => item.name === name); if (parameter < 0) this.fail(i, "type", `알 수 없는 키워드 인수 '${name}'입니다.`); if (assigned.has(name)) this.fail(i, "type", `인수 '${name}'이(가) 중복 전달되었습니다.`); locals.set(name, value); assigned.add(name); } let defaultIndex = 0; for (const parameter of fn.params) { if (parameter.hasDefault) { const value = fn.defaults[defaultIndex++]; if (!assigned.has(parameter.name)) locals.set(parameter.name, value); } else if (!assigned.has(parameter.name)) this.fail(i, "type", `필수 인수 '${parameter.name}'이(가) 없습니다.`); } this.frames.push({ bytecode: this.bytecode, pc: this.pc, stack: this.stack, env: this.env, outerEnvs: this.outerEnvs, localNames: this.localNames, globalNames: this.globalNames, functionName: fn.name }); this.activeFunctions.push(fn.name); this.bytecode = fn.bytecode; this.pc = 0; this.stack = []; this.env = locals; this.outerEnvs = []; this.localNames = new Set(fn.localNames); this.globalNames = new Set(fn.globals); }
  private returnFromFunction(value: Value): void { const frame = this.frames.pop(); if (!frame) { this.stack.push(value); return; } this.withFiles = this.withFiles.filter(item => { if (item.depth > this.frames.length) { this.close(item.file); return false; } return true; }); this.bytecode = frame.bytecode; this.pc = frame.pc; this.stack = frame.stack; this.env = frame.env; this.outerEnvs = frame.outerEnvs; this.localNames = frame.localNames; this.globalNames = frame.globalNames; if (frame.functionName !== undefined) this.activeFunctions.pop(); const pending=this.pendingInstances.at(-1);if(pending&&this.frames.length===pending.depth){this.pendingInstances.pop();if(value!==null)this.fail(pending.instruction,"type","__init__()은 값을 반환할 수 없습니다.");this.stack.push(pending.instance);return;} this.stack.push(value); }
  private callFunctionSync(i: Instruction, fn: FunctionValue, args: Value[]): Value { const depth = this.frames.length; this.callFunction(i, fn, args, {}); while (this.frames.length > depth && !this.waiting && !this.stopped) { const instruction = this.bytecode.instructions[this.pc++]; if (!instruction) this.fail(i, "runtime", "함수 실행 중 오류가 발생했습니다."); this.step(instruction); } if (this.waiting) this.fail(i, "runtime", "map() 안의 input()은 지원하지 않습니다."); return this.pop(i); }
  private stringValue(i: Instruction, value: Value): string { if (typeof value === "string") return value; if (isException(value)) return value.message; if (isInstance(value)) { const method = value.classValue.attributes.get("__str__"); if (method !== undefined) { if (!isFunction(method)) this.fail(i, "type", "__str__은 메서드여야 합니다."); const result = this.callFunctionSync(i, method, [value]); if (typeof result !== "string") this.fail(i, "type", "__str__()은 문자열을 반환해야 합니다."); return result; } } return printable(value); }
  private items(i:Instruction,v:Value):Value[]{if(isMap(v)){const values:Value[]=[];let value:Value|undefined;while((value=this.next(i,v))!==undefined)values.push(value);return values;}if(isIterator(v)){const values=v.values.slice(v.index);v.index=v.values.length;return values;}if(typeof v==="string")return[...v];if(isList(v)||isTuple(v))return v.items;if(isDict(v))return v.entries.map(e=>e.key);if(isRange(v))return this.rangeItems(i,v);this.fail(i,"type","이 값은 여러 개로 나눌 수 없습니다.");}
  private subscript(i:Instruction,o:Value,k:Value):Value{if(isSlice(k)){const step=k.step??1;if(step===0)this.fail(i,"value","슬라이스 간격은 0이 될 수 없습니다.");const a=this.items(i,o),start=k.start??(step>0?0:a.length-1),stop=k.stop??(step>0?a.length:-a.length-1),out:Value[]=[];for(let x=start<0?start+a.length:start;step>0?x<(stop<0?stop+a.length:stop):x>(stop<0?stop+a.length:stop);x+=step)if(x>=0&&x<a.length)out.push(a[x]);return typeof o==="string"?out.map(x=>x as string).join(""):isTuple(o)?{kind:"tuple",items:out}:{kind:"list",items:out};}if(isDict(o)){const found=o.entries.find(e=>equal(e.key,k));if(!found)this.fail(i,"value",`딕셔너리에 ${repr(k)} 키가 없습니다.`);return found.value;}if(typeof k!=="number"||!Number.isInteger(k))this.fail(i,"type","인덱스는 정수여야 합니다.");const a=this.items(i,o),x=k<0?a.length+k:k;if(x<0||x>=a.length)this.fail(i,"value",`값에 ${k}번 위치의 값이 없습니다.`);return a[x];}
  private setSubscript(i:Instruction,o:Value,k:Value,v:Value):void{if(isList(o)){if(typeof k!=="number"||!Number.isInteger(k))this.fail(i,"type","인덱스는 정수여야 합니다.");const x=k<0?o.items.length+k:k;if(x<0||x>=o.items.length)this.fail(i,"value",`리스트에 ${k}번 위치의 값이 없습니다.`);o.items[x]=v;return;}if(isDict(o)){if(!keyOK(k))this.fail(i,"type","변경 가능한 값은 딕셔너리 키가 될 수 없습니다.");const found=o.entries.find(e=>equal(e.key,k));if(found)found.value=v;else o.entries.push({key:k,value:v});return;}this.fail(i,"type","이 값의 요소는 수정할 수 없습니다.");}
  private method(i:Extract<Instruction,{op:"call_method"}>,o:Value,n:string,a:Value[]):void{if(isFile(o)){if(n==="read"&&(a.length===0||a.length===1)){this.stack.push(this.fileRead(i,o,a[0]));return;}if(n==="readline"&&a.length===0){if(o.closed)this.fail(i,"value","닫힌 파일은 사용할 수 없습니다.");if(o.mode!=="r")this.fail(i,"type","쓰기 모드로 연 파일에서는 읽을 수 없습니다.");this.stack.push(this.fileLine(o));return;}if(n==="readlines"&&a.length===0){if(o.closed)this.fail(i,"value","닫힌 파일은 사용할 수 없습니다.");if(o.mode!=="r")this.fail(i,"type","쓰기 모드로 연 파일에서는 읽을 수 없습니다.");this.stack.push({kind:"list",items:this.fileLines(o)});return;}if(n==="write"&&a.length===1){this.stack.push(this.fileWrite(i,o,a[0]));return;}if(n==="close"&&a.length===0){this.close(o);this.stack.push(null);return;}this.fail(i,"name",`파일에서 '${n}' 메서드를 사용할 수 없습니다.`);}if(isList(o)){if(n==="append"&&a.length===1){o.items.push(a[0]);this.stack.push(null);return;}if(n==="pop"&&a.length<=1){if(!o.items.length)this.fail(i,"value","빈 리스트에서 pop할 수 없습니다.");const p=a.length?(typeof a[0]==="number"?a[0]:this.fail(i,"type","pop 인덱스는 정수여야 합니다.")):-1;this.stack.push(o.items.splice(p<0?o.items.length+p:p,1)[0]);return;}if(n==="remove"&&a.length===1){const x=o.items.findIndex(v=>equal(v,a[0]));if(x<0)this.fail(i,"value","리스트에 해당 값이 없습니다.");o.items.splice(x,1);this.stack.push(null);return;}}if(isDict(o)){if(n==="keys"&&a.length===0){this.stack.push({kind:"list",items:o.entries.map(e=>e.key)});return;}if(n==="values"&&a.length===0){this.stack.push({kind:"list",items:o.entries.map(e=>e.value)});return;}if(n==="items"&&a.length===0){this.stack.push({kind:"list",items:o.entries.map(e=>({kind:"tuple",items:[e.key,e.value]}))});return;}if(n==="get"&&(a.length===1||a.length===2)){this.stack.push(o.entries.find(e=>equal(e.key,a[0]))?.value??(a[1]??null));return;}}if(typeof o==="string"){if(n==="split"&&a.length<=1){const s=a[0];if(s!==undefined&&typeof s!=="string")this.fail(i,"type","split 구분자는 문자열이어야 합니다.");this.stack.push({kind:"list",items:s===undefined?o.trim().split(/\s+/).filter(Boolean):o.split(s)});return;}if(n==="strip"&&a.length===0){this.stack.push(o.trim());return;}if(n==="replace"&&a.length===2&&typeof a[0]==="string"&&typeof a[1]==="string"){this.stack.push(o.split(a[0]).join(a[1]));return;}}this.fail(i,"name",`'${n}' 메서드를 사용할 수 없습니다.`);}
  private binary(i: Extract<Instruction, { op: "binary" }>, left: Value, right: Value): Value { if (i.operator === "+" && typeof left === "string" && typeof right === "string") return left + right; if ((isList(left)&&isList(right))||(isTuple(left)&&isTuple(right)))return {kind:isList(left)?"list":"tuple",items:[...(left as typeof left).items,...(right as typeof right).items]} as Value;if ((isList(left)||isTuple(left))&&typeof right==="number"&&Number.isInteger(right))return {kind:isList(left)?"list":"tuple",items:Array.from({length:Math.max(0,right)},()=>left.items).flat()} as Value; if (i.operator === "*" && typeof left === "string" && typeof right === "number" && Number.isInteger(right)) return left.repeat(Math.max(0, right)); if (i.operator === "*" && typeof right === "string" && typeof left === "number" && Number.isInteger(left)) return right.repeat(Math.max(0, left)); if (typeof left !== "number" || typeof right !== "number") this.fail(i, "type", "이 연산에는 같은 종류의 값을 사용해야 합니다."); if (["/", "//", "%"].includes(i.operator) && right === 0) this.fail(i, "value", "0으로 나눌 수 없습니다."); switch (i.operator) { case "+": return left + right; case "-": return left - right; case "*": return left * right; case "/": return left / right; case "//": return Math.floor(left / right); case "%": return left - Math.floor(left / right) * right; case "**": return left ** right; default: return this.fail(i, "runtime", "지원하지 않는 연산입니다."); } }
  private compare(i: Extract<Instruction, { op: "compare" }>, operator: string, left: Value, right: Value): boolean { if (operator === "==") return equal(left, right); if (operator === "!=") return !equal(left, right); if (isDate(left) && isDate(right)) { left = left.year * 10000 + left.month * 100 + left.day; right = right.year * 10000 + right.month * 100 + right.day; } if ((typeof left !== "number" && typeof left !== "string") || (typeof right !== "number" && typeof right !== "string") || typeof left !== typeof right) this.fail(i, "type", "비교할 수 없는 값입니다."); const a = left as number | string, b = right as number | string; switch (operator) { case "<": return a < b; case "<=": return a <= b; case ">": return a > b; case ">=": return a >= b; default: return false; } }
  private invoke(i: Instruction, callable: Value, args: Value[], keywords: Record<string, Value>): void {
    if (isTurtleMethod(callable)) { this.stack.push(this.library(i, () => this.modules.turtleMethod(callable, args, keywords))); return; }
    if (isBoundMethod(callable)) { this.callFunction(i, callable.functionValue, [callable.instance, ...args], keywords); return; }
    if (isClass(callable)) { const instance: Extract<Value,{kind:"instance"}> = {kind:"instance",classValue:callable,attributes:new Map()}; const init=callable.attributes.get("__init__"); if(init===undefined){if(args.length||Object.keys(keywords).length)this.fail(i,"type",`${callable.name}()은 인수를 받을 수 없습니다.`);this.stack.push(instance);return;} if(!isFunction(init))this.fail(i,"type","__init__은 메서드여야 합니다.");const depth=this.frames.length;this.pendingInstances.push({depth,instance,instruction:i});this.callFunction(i,init,[instance,...args],keywords);return; }
    if (isFunction(callable)) { this.callFunction(i, callable, args, keywords); return; }
    if (!isBuiltin(callable)) this.fail(i, "type", "이 값은 함수처럼 호출할 수 없습니다.");
    const name = callable.name;
    if (name.startsWith("random.") || name.startsWith("datetime.") || name.startsWith("turtle.")) { this.stack.push(this.library(i, () => this.modules.invoke(name, args, keywords))); return; }
    if (name === "open") { this.openFile(i, args, keywords); return; }
    const onlyNoKeywords = () => { if (Object.keys(keywords).length) this.fail(i, "type", "이 함수는 키워드 인수를 지원하지 않습니다."); };
    if (name === "input") { onlyNoKeywords(); if (args.length > 1) this.fail(i, "type", "input() 인수가 너무 많습니다."); if (args[0] !== undefined && typeof args[0] !== "string") this.fail(i, "type", "input()의 프롬프트는 문자열이어야 합니다."); this.waiting = true; this.notify({ type: "input", prompt: (args[0] as string | undefined) ?? "" }); return; }
    if (name === "print") { const allowed = new Set(["sep", "end"]); if (Object.keys(keywords).some(key => !allowed.has(key))) this.fail(i, "type", "print()에 지원하지 않는 키워드 인수가 있습니다."); const sep = keywords.sep === undefined ? " " : keywords.sep, end = keywords.end === undefined ? "\n" : keywords.end; if (typeof sep !== "string" || typeof end !== "string") this.fail(i, "type", "sep와 end는 문자열이어야 합니다."); const text = args.map(value=>this.stringValue(i,value)).join(sep) + end; if (this.outputSize + text.length > MAX_OUTPUT) this.systemFail(i, "출력량 제한을 초과했습니다."); this.outputSize += text.length; this.notify({ type: "output", text }); this.stack.push(null); return; }
    if (name === "range") { onlyNoKeywords(); if (args.length < 1 || args.length > 3 || args.some(value => typeof value !== "number" || !Number.isInteger(value))) this.fail(i, "type", "range()에는 정수 인수 1~3개가 필요합니다."); const [first, second, third] = args as number[]; const start = args.length === 1 ? 0 : first, stop = args.length === 1 ? first : second, step = args.length === 3 ? third : 1; if (step === 0) this.fail(i, "value", "range()의 간격은 0이 될 수 없습니다."); this.stack.push({ kind: "range", start, stop, step }); return; }
    if (name === "map") { onlyNoKeywords(); if (args.length < 2) this.fail(i, "type", "map()은 함수와 반복 가능한 값이 필요합니다."); if (!isBuiltin(args[0]) && !isFunction(args[0])) this.fail(i, "type", "map()의 첫 번째 인수는 호출할 수 있어야 합니다."); this.stack.push({ kind: "map", fn: args[0], sources: args.slice(1).map(value => this.iterator(i, value)) }); return; }
    if (["len","list","tuple","dict","sum","min","max"].includes(name)) { onlyNoKeywords(); if(name==="list"&&args.length===0){this.stack.push({kind:"list",items:[]});return;}if(name==="tuple"&&args.length===0){this.stack.push({kind:"tuple",items:[]});return;}if(name==="dict"&&args.length===0){this.stack.push({kind:"dict",entries:[]});return;}if(name==="min"||name==="max"){const values=args.length===1?this.items(i,args[0]):args;if(!values.length)this.fail(i,"value",`빈 값에서는 ${name==="min"?"최솟값":"최댓값"}을 구할 수 없습니다.`);if(!values.every(v=>typeof v==="number"||typeof v==="string"))this.fail(i,"type","서로 비교할 수 없는 값입니다.");this.stack.push(values.reduce((a,b)=>name==="min"?(a as string|number)<(b as string|number)?a:b:(a as string|number)>(b as string|number)?a:b));return;}if(name==="sum"){if(args.length<1||args.length>2)this.fail(i,"type","sum()은 인수 1~2개가 필요합니다.");const values=this.items(i,args[0]);if(!values.every(v=>typeof v==="number"||typeof v==="boolean"))this.fail(i,"type","sum()에는 숫자만 사용할 수 있습니다."); const start = args[1] === undefined ? 0 : typeof args[1] === "number" || typeof args[1] === "boolean" ? Number(args[1]) : this.fail(i,"type","시작값은 숫자여야 합니다."); this.stack.push(values.reduce<number>((a,b)=>a+Number(b),start));return;}if(args.length!==1)this.fail(i,"type",`${name}()은 인수 1개가 필요합니다.`);const v=args[0];if(name==="len"){this.stack.push(this.items(i,v).length);return;}if(name==="list"){this.stack.push({kind:"list",items:this.items(i,v).slice()});return;}if(name==="tuple"){this.stack.push({kind:"tuple",items:this.items(i,v).slice()});return;}if(name==="dict"){if(isDict(v)){this.stack.push({kind:"dict",entries:v.entries.slice()});return;}const entries:{key:Value;value:Value}[]=[];for(const pair of this.items(i,v)){const p=this.items(i,pair);if(p.length!==2||!keyOK(p[0]))this.fail(i,"type","dict() 항목은 키와 값 두 개여야 합니다.");entries.push({key:p[0],value:p[1]});}this.stack.push({kind:"dict",entries});return;}}
    onlyNoKeywords(); if (name === "bool" && args.length === 0) { this.stack.push(false); return; } if (args.length !== 1) this.fail(i, "type", `${name}()은(는) 인수 하나가 필요합니다.`); const value = args[0];
    if (name === "int") { if (typeof value === "number") { this.stack.push(Math.trunc(value)); return; } if (typeof value === "boolean") { this.stack.push(value ? 1 : 0); return; } if (typeof value !== "string") this.fail(i, "type", "정수로 변환할 수 없습니다."); const number = Number(value.trim()); if (!Number.isFinite(number) || !Number.isInteger(number)) this.fail(i, "value", "정수로 변환할 수 없습니다."); this.stack.push(number); return; }
    if (name === "float") { if (typeof value === "boolean") { this.stack.push(value ? 1 : 0); return; } if (typeof value !== "number" && typeof value !== "string") this.fail(i, "type", "실수로 변환할 수 없습니다."); const number = Number(value); if (!Number.isFinite(number)) this.fail(i, "value", "실수로 변환할 수 없습니다."); this.stack.push(number); return; }
    if (name === "str") { this.stack.push(this.stringValue(i,value)); return; } if (name === "bool") { this.stack.push(truthy(value)); return; } if (name === "type") { this.stack.push(`<class '${typeName(value)}'>`); return; } this.fail(i, "name", `'${name}' 함수가 정의되지 않았습니다.`);
  }
}
class VMFailure { constructor(readonly error: StudentError, readonly type: string, readonly catchable = true) {} }
