import { readFile, writeFile } from 'node:fs/promises';
import { duplicateAliases } from './cases/index.mjs';
const path='artifacts/python-compatibility-audit-v2', d=JSON.parse(await readFile(path+'.json','utf8'));
const b=JSON.parse(await readFile('artifacts/python-compatibility-browser/results.json','utf8'));
for(const r of b.results)if(duplicateAliases[r.id]){r.originalAuditId=r.id;r.id=duplicateAliases[r.id];}
const fields=['exact','educational-compatible','intentional-difference','interpreter-defect','unsupported'];
const labels={'exact':'정확히 일치','educational-compatible':'교육 목적상 호환','intentional-difference':'의도적인 차이','interpreter-defect':'인터프리터 결함','unsupported':'미지원'};
const categoryLabels={legacy:'기존 52개 재검사',numeric:'숫자·연산',evaluation:'평가 순서',comparison:'비교·동일성·논리',string:'문자열·Unicode',collection:'컬렉션',assignment:'대입·언패킹·슬라이싱',control:'조건·반복·제어',function:'함수·스코프·재귀',exception:'예외·finally',class:'클래스·상속',builtin:'반복자·내장 함수',module:'사용자 모듈',math:'math',standard:'random·datetime', 'file-output':'파일·출력·f-string',safety:'안전 제한(별도)'};
function review(r){
 const id=r.id;
 let group='기타 지원 의미',severity='P2',cause='지원 경로의 CPython 의미 처리가 일부 생략됨',source='src/runtime/vm.ts',impact='해당 경계 입력의 결과/오류를 CPython과 다르게 학습할 수 있음',difficulty='중',recommendation='원시 결과에 있는 최소 사례를 회귀 테스트로 먼저 고정한 뒤 별도 승인 작업에서 수정';
 if(/^numeric-operation-(45|46|47)$/.test(id)){group='int 문자열 검증';severity='P1';cause='int가 Python 정수 문자열 문법 대신 Number() 변환을 허용';impact='소수 문자열·빈 입력·기본 진법이 아닌 입력을 정상 정수로 수용하여 입력 검증 실패';difficulty='하';}
 else if(/numeric-operation-(54|55)|numeric-float-(floor-edge|modulo-edge)/.test(id)){group='실수 floor/mod/divmod';severity='P1';source='src/runtime/vm.ts; src/runtime/builtins-v2.ts';cause='Math.floor(a/b)와 a-floor(a/b)*b 방식이 CPython float divmod 보정과 다름';impact='작은 일반 소수에서도 몫이 1 다르거나 나머지를 0으로 오판';}
 else if(/evaluation-(assign|chain|unpack|augmented)$/.test(id)){group='함수 호출 결과를 포함한 대입 대상';severity='P1';source='src/compiler/parser.ts';cause='statement/target 인식이 호출 표현식 뒤 첨자 대입을 정상 target으로 수용하지 못함';impact='유효한 첨자 대입·연속 대입·복합 대입이 실행 전에 SyntaxError로 거절';}
 else if(id==='evaluation-compare-short'){group='비교 연쇄 단락 평가';severity='P1';source='src/compiler/compiler.ts:31';cause='비교 바이트코드 전에 operands.forEach(expression)으로 모든 피연산자를 평가';impact='이미 거짓인 연쇄 비교 뒤 함수 호출/입력/부작용도 발생';}
 else if(/comparison-value-(7|8|17|18)$|collection-set-subset/.test(id)){group='컬렉션 순서·부분집합 비교';severity='P1';cause='sorted용 compareValues와 일반 비교 연산자의 허용 타입 경로가 일치하지 않음';impact='리스트·튜플 사전식 비교와 집합 부분집합 연산이 TypeError';}
 else if(id==='comparison-value-21'){group='빈 range의 참·거짓';severity='P1';source='src/runtime/value.ts:truthy';cause='truthy 함수에 RangeValue 길이 검사 없음';impact='빈 range를 조건식에 쓰면 참 분기로 실행';difficulty='하';}
 else if(id==='collection-dict-nan-key'){group='NaN 키 동일 객체 조회';source='src/runtime/value.ts:equal; src/runtime/vm.ts';cause='키 검색이 동일 객체 단축 검사 없이 NaN===NaN 비교로 귀결';impact='방금 넣은 동일 NaN 객체 키를 찾지 못함';}
 else if(/collection-(dict|set)-modification/.test(id)){group='반복 중 크기 변경 감지';severity='P1';cause='순회 스냅샷/배열 인덱스에 변경 버전 검증이 없음';impact='CPython RuntimeError 대신 조용히 다른 경로로 완료';}
 else if(/assignment-(slice-assign|step-assign|step-size)/.test(id)){group='슬라이스 대입';severity='P1';cause='슬라이스 읽기·삭제와 달리 store_subscript는 정수 인덱스만 허용';impact='리스트 구간/step 대입이 실패. 지원 표가 읽기만 뜻한다면 문서 명시도 필요';recommendation='지원 범위를 먼저 명확히 하고, 쓰기도 지원할 경우 길이 검증과 참조 유지 테스트부터 추가';}
 else if(id==='assignment-aug-list-ref'){group='리스트 += 참조 유지';severity='P1';source='src/compiler/compiler.ts:162; src/runtime/vm.ts';cause='augassign을 일반 binary +와 store로 컴파일하여 새 리스트 생성';impact='같은 리스트를 가리키던 다른 변수에서 변경이 사라짐';}
 else if(id==='assignment-index-bool'){group='bool 인덱스';cause='정수 인덱스 검사에서 bool을 int 하위 의미로 변환하지 않음';impact='True/False 인덱스의 유효한 접근 거부';difficulty='하';}
 else if(id==='function-global-order'){group='global 선언 순서 검사';severity='P1';source='src/compiler/compiler.ts; src/compiler/parser.ts';cause='사용 이후 global 선언을 컴파일 단계에서 검증하지 않음';impact='CPython이 거절하는 프로그램을 정상 실행';}
 else if(id==='function-invalid-nonlocal'){group='nonlocal 오류 위치';source='src/compiler/compiler.ts; src/runtime/vm.ts';cause='nonlocal 바인딩 검증을 함수 생성 시 수행하며 def 토큰 위치를 사용';impact='오류 줄을 nonlocal 문장이 아닌 def 문장으로 표시';difficulty='하';}
 else if(id==='function-local-before-assignment'){group='지역 변수 예외 클래스';cause='지역 미초기화 오류를 UnboundLocalError가 아닌 NameError로 매핑';impact='세부 예외 종류 학습과 해당 except 분기 동작 차이';}
 else if(id==='builtin-map-bound'){group='map 결합 메서드 콜백';severity='P1';cause='map 첫 인수 검사가 builtin/function만 허용하며 bound-method를 제외';impact='기존 결합 메서드를 map에 전달하는 정상 코드 실패';}
 else if(id==='builtin-call-34'){group='빈 sum의 시작값';cause='입력 iterable이 비어 있어도 start를 먼저 숫자로 제한';impact='sum([], None)는 CPython의 None 대신 TypeError';difficulty='하';}
 else if(/^string-repr-|file-output-readlines/.test(id)){group='문자열 컬렉션 repr 이스케이프';severity='P2';source='src/runtime/value.ts:repr';cause='문자열 repr에서 따옴표 외 역슬래시·개행·탭 이스케이프를 생략';impact='목록 표시가 여러 줄로 깨지고 파일 라인/제어 문자 표현이 오해를 줌';difficulty='하';}
 else if(/^file-output-(read|readline|append)$/.test(id)){group='파일 universal newline';severity='P2';cause='CPython 텍스트 모드 CRLF→LF 정규화 없이 원문 문자열 반환';impact='strip을 쓰는 CSV는 동작하지만 정확한 내용/줄바꿈 비교 차이';}
 else if(id==='file-output-write'||id==='file-output-read-emoji'){group='파일 Unicode 코드 포인트 위치';severity='P1';cause='파일 position/read/write 길이를 JS UTF-16 code unit으로 계산';impact='비 BMP 문자를 반쪽 surrogate로 읽거나 write 반환 글자 수가 다름';}
 else if(id==='file-output-print-none-sep'){group='print sep=None';cause='None을 기본 공백으로 처리하지 않고 문자열만 허용';impact='정상적인 기본 구분자 선택을 TypeError로 거절';difficulty='하';}
 else if(/file-output-(write-read-mode|read-write-mode)/.test(id)){group='파일 모드 예외 클래스';cause='io.UnsupportedOperation 계열 대신 TypeError 사용';impact='표준 파일 모드 오류 처리와 예외 종류가 다름';}
 else if(r.differences.length===1&&r.differences[0]==='errorType'){group='숫자·math 예외 클래스';source='src/runtime/math-v2.ts; src/runtime/builtins-v2.ts; src/runtime/vm.ts';cause='OverflowError/ZeroDivisionError를 포괄적인 ValueError로 매핑';impact='계산 중단은 되지만 예외 종류와 except 선택이 달라짐';}
 return {group,severity,cause,source,impact,difficulty,recommendation};
}
for(const r of d.results){if(r.classification==='interpreter-defect')r.review=review(r);if(r.numeric&&/^[+-]?\d+$/.test(r.cpython.stdout.trim())&&/^[+-]?\d+$/.test(r.learningVm.stdout.trim())){const delta=BigInt(r.cpython.stdout.trim())-BigInt(r.learningVm.stdout.trim());r.numeric.integerDelta=String(delta);r.numeric.integerExact=delta===0n;}}
d.browser={...b,results:b.results};d.environment.browser=b.browser;d.environment.launcherChecks={'python --version':'실행 실패, exit 9009 (Windows alias)','py -3 --version':'Python 3.14.6',selectedReason:'기존 52개 검증 기준과 동일한 CPython 3.12.14 명시 경로를 고정; 3.14.6과 혼합하지 않음'};
d.measurementPolicy={denominator:'작성한 호환성 검사 사례 중 일치율 (Python 전체 지원률 아님)',totalIncludesVmOnly:d.vmOnly,stdout:'실제 stdout, input prompt 포함; terminal echo와 앱 상태 메시지는 제외',errors:'종류·파일 basename·줄 비교; 한국어/영어 문구 차이는 허용; 열은 기록만 함',compilerErrors:'VM CompilerError의 syntax/unsupported category는 비교용 SyntaxError로 표준화; 원래 category 별도 보존',columns:'CPython 열은 UTF-8 byte offset 기반일 수 있고 VM은 토큰 위치이므로 숫자만으로 결함 판단하지 않음',numeric:'repr/text 일치와 abs/rel 오차를 분리. 안전 정수 경계는 문자열/BigInt로 검증',safety:'모든 안전 제한 사례는 별도 intentional-difference. CPython 무한 루프/Tk GUI 3개는 실행하지 않음',scopeAmbiguity:'원래 Core v2 요청의 슬라이싱 절은 step 조회 확장이며 쓰기는 포함하지 않으므로 슬라이스 대입 3개를 미지원으로 분류. 읽기/삭제와 구분하여 안내 필요'};
d.measurementPolicy.deduplication={duplicateAliases,method:'CPython AST 및 동일 입력/파일로 교차 분야 중복 7개 제거. 0.0과 1e-324는 서로 다른 lexer/underflow 경로이므로 유지'};
const sev={};for(const r of d.results.filter(r=>r.review))sev[r.review.severity]=(sev[r.review.severity]??0)+1;d.defectSeverities=sev;d.defectGroups=[...new Set(d.results.filter(r=>r.review).map(r=>r.review.group))];
await writeFile(path+'.json',JSON.stringify(d,null,2));
const csvFields=['id','category','feature','classification','severity','code','input','files','cpythonStdoutJson','vmStdoutJson','cpythonError','vmError','cpythonFile','cpythonLine','cpythonColumn','vmFile','vmLine','vmColumn','cpythonCompletion','vmCompletion','differences','numeric','notes'];
const quote=x=>'"'+String(x??'').replaceAll('"','""')+'"';
const csv=[csvFields.map(quote).join(',')];for(const r of d.results)csv.push([r.id,r.category,r.feature,r.classification,r.review?.severity,r.code,JSON.stringify(r.input),JSON.stringify(r.files),JSON.stringify(r.cpython.stdout),JSON.stringify(r.learningVm.stdout),r.cpython.errorType,r.learningVm.errorType,r.cpython.file,r.cpython.line,r.cpython.column,r.learningVm.file,r.learningVm.line,r.learningVm.column,r.cpython.completion,r.learningVm.completion,r.differences.join(';'),JSON.stringify(r.numeric),r.notes].map(quote).join(','));await writeFile(path+'.csv','\ufeff'+csv.join('\r\n'));
const pct=n=>(n/d.total*100).toFixed(2)+'%', md=[];
md.push('# Python 학습실 v2.0.0 CPython 정밀 호환성 감사','', '## 실행 환경','',`- 커밋: \`${d.environment.commit}\`; 앱 ${d.environment.version}; 앱/기존 테스트/버전 수정 없음. 커밋·push·배포·태그·Release 없음.`, `- CPython: ${d.environment.cpython.python}; 실행 파일: \`${d.environment.python}\`.`, '- python --version은 Windows alias 실행 실패(exit 9009). py -3은 3.14.6. 기존 비교 기준을 유지하기 위해 명시 경로 3.12.14만 사용.',`- Node ${d.environment.node}; npm 11.16.0; ${d.environment.os}; 시간대 ${d.environment.timezone}.`, `- Edge ${b.browser}; 로컬 프로덕션 ${b.url}; PC 1440×900 / 모바일 360×800.`, `- CPython Unicode ${d.environment.cpython.unicode}; Node Unicode ${d.environment.unicodeJS}. 실행 시각 ${d.environment.time}.`, '', '## 전체 결과','',`총 ${d.total}개 독립 사례: CPython/VM 양쪽 실행 ${d.comparisonDenominator}개, VM-only 안전/GUI 확인 ${d.vmOnly}개. 기존 52개를 포함한다. 안전용 VM-only 사례를 제외해도 최소 300개를 충족한다.`, '', '**아래 비율은 작성한 호환성 검사 사례 중 일치율이다. Python 전체의 지원률이 아니다.** 경계값과 잘못된 입력을 의도적으로 많이 포함했으므로 실제 수업 코드 분포의 추정치도 아니다.','', '| 분류 | 사례 수 | 비율 |','|---|---:|---:|');
for(const f of fields)md.push(`| ${labels[f]} | ${d.counts[f]??0} | ${pct(d.counts[f]??0)} |`);
md.push('', `정확 일치+교육 목적 호환: ${d.counts.exact+d.counts['educational-compatible']}/${d.total} (${pct(d.counts.exact+d.counts['educational-compatible'])}). 오류의 한국어 메시지/traceback 표현만 다른 경우 교육 목적 호환으로 분류한다. 기존 52개는 stdout/오류 클래스 기준 모두 유지되며 이 감사 분류로는 50 exact + 2 educational-compatible이다.`, '', '## 분야별 결과','', '| 분야 | 검사 | exact | 교육 호환 | 의도적 차이 | 결함 | 미지원 |','|---|---:|---:|---:|---:|---:|---:|');
for(const [cat,counts]of Object.entries(d.categories))md.push(`| ${categoryLabels[cat]??cat} | ${counts.total} | ${fields.map(f=>counts[f]??0).join(' | ')} |`);
md.push('', '기존 52개는 별도 한 분야로 집계하여 다른 분야에 중복 계산하지 않았다. math/사용자 모듈/random·datetime은 세부 분류를 나눴다. 각 신규 사례는 한 쟁점만 다루며 초기 52개의 복합 사례는 원문을 보존했다.', '', '## 비교 기준과 재현 방법','', '- 감사 도구: audit/python-compatibility/. CPython 한 사례마다 별도 프로세스, 5초 timeout, 2MB 출력 버퍼. 실제 파일은 artifacts/python-compatibility-work/<id> 아래에서만 생성. VM은 새 인스턴스와 격리된 VFS 사용.', '- 모든 코드·입력·파일·원시 stdout·오류 클래스·파일·줄·열·완료 상태·파일 변경 결과는 JSON/CSV에 보존. Markdown의 문자열 결과는 JSON escape로 개행/탭을 구분한다.', '- 오류 문장의 언어와 호스트 traceback은 직접 동일 비교하지 않음. CPython 오류 위치는 마지막 학생 파일 프레임, VM 위치는 원본 StudentError 사용. 열은 토큰 범위/UTF-8 차이 때문에 정보로만 기록.', '- 안전한 대표 input을 동일하게 공급. VM의 input prompt는 CPython과 비교하되 브라우저 입력 echo를 별도로 제거. 앱 자체 실행 상태 문구는 stdout에 포함하지 않음.', '- 숫자값 허용 오차는 abs 1e-12 + rel 1e-12로 별도 기록하며 repr 차이를 덮지 않음. 정수는 출력 문자열 및 BigInt 차이로 검증하여 Number 변환이 정밀도 손실을 숨기지 않게 함.', '- 집합 출력 순서는 보장되지 않아 원소 의미를 따로 비교. 난수열은 알고리즘 차이를 분리하고 동일 seed 재현성·범위·비복원 추출을 검사.', '- 감사 1차 전체 측정 후 추가 경계만 --reuse로 실행. 재사용은 같은 커밋·동일 코드/입력/파일인 원시 결과만 허용. 기본 명령은 전체 새 실행.', '', '## 경계값 표','', '| 경계 | CPython | 학습 VM | 해석 |','|---|---|---|---|', '| 정수 2**53−1 = 9007199254740991 | 정확 | 정확 | 문서화된 안전 범위 끝 |','| 정수 2**53 = 9007199254740992 | 정확 | 정확 | 범위 밖이지만 이 짝수 자체는 표현 가능 |','| 정수 2**53+1 = 9007199254740993 | 9007199254740993 | 9007199254740992 | 양의 연속 정수 표현 최초 차이; 음수도 −9007199254740993에서 차이 |','| 실수 1.0//0.2 | 4.0 | 5.0 | 극단값 이전의 일반 계산에서도 의미 차이 |','| 실수 1.0//0.1, 1.0%0.1 | 9.0 / 0.09999999999999995 | 10.0 / 0.0 | CPython float divmod 보정 누락 |','| 실수 1e−324 / 5e−324 / 1e−300 / 1e300 | 대표 표현 | 동일 | 실수 전체에 대해 하나의 크기 경계가 있다고 볼 수 없음 |','| 단순 재귀 f(n) | n=997 완료, n=998 실패 | n=127 완료, n=128 실패 | 이 oracle wrapper 기준. CPython sys limit=1000, VM frame limit=128 |','| list(range(n)) | n=10002도 완료 | n=10001 완료, n=10002 제한 | range 물질화 경로는 문서 10000과 1 차이 |','| [0]*n | n=10001 완료 | 10000 완료, 10001 제한 | 컬렉션 생성 경로별 실제 상한 다름 |','| for range(n) 누적 | n=10000 완료 | 9999 완료, 10000 제한 | 루프 진입/종료 검사도 guard 수에 포함 |','| 출력 | 100001 문자도 완료 | 100000까지 허용, 초과 전체 chunk 차단 | 학생 except로 잡을 수 없는 신호 |','| 명령 실행 | 유한 1,999,800 증분 완료 | 1,000,000 명령 제한 | 반복 제한보다 먼저 발동하는 유한 사례로 확인 |','| math.factorial | 19도 계산 | 최대 18 | 의도적 정수 정밀도 제한 |','| VFS 파일 | 디스크 파일 생성/쓰기 | 100파일 / 파일당 1,000,000바이트 | 실제 한도 초과 검사, 사용자 디스크 파일 미접근 |','', 'Unicode에서 일반 한글·emoji 문자열 인덱싱은 일치하지만 파일 read(1)은 emoji surrogate를 분리한다. ǅ의 title/capitalize 및 ①의 isdigit 차이는 README에 명시된 드문 Unicode 판별/대소문자 차이로 분리했다. 이는 정확히 일치한 것으로 세지 않았다.', '', '## 발견한 결함','',`결함으로 분류한 **${d.counts['interpreter-defect']}개 사례**, 중복 근본 원인은 **${d.defectGroups.length}개 묶음**이다. 사례 수를 독립 버그 개수로 오해하지 않아야 한다. 심각도별 사례: ${JSON.stringify(sev)}. 이번 검사에서 P0는 발견하지 않았으나 모든 프로그램의 데이터 안전성을 증명한 것은 아니다. 어떤 결함도 수정하지 않았다.`, '', '원래 Core v2 구현 요청의 슬라이싱 절은 start:stop:step 조회 확장이었다. 슬라이스 대입 3사례는 미지원으로 보수적으로 분류하고 읽기/삭제와 구분했다. 중첩 언패킹의 전체 대상 사전 검증도 기존 자동 테스트가 명시한 의도적인 부분 저장 방지 정책이므로 결함으로 세지 않았다.');
for(const r of d.results.filter(r=>r.review)){
 md.push('',`### ${r.review.severity} · ${r.id} — ${r.review.group}`,'','```python',r.code,'```');
 if(r.files.length)md.push('',`필요한 자체 작성 파일: ${r.files.map(f=>f.name).join(', ')} (내용은 JSON/CSV에 포함).`);
 md.push('',`- CPython: stdout=${JSON.stringify(r.cpython.stdout)}; ${r.cpython.errorType??'정상'}${r.cpython.line?` (${r.cpython.file}:${r.cpython.line})`:''}.`,`- 학습 VM: stdout=${JSON.stringify(r.learningVm.stdout)}; ${r.learningVm.errorType??'정상'}${r.learningVm.line?` (${r.learningVm.file}:${r.learningVm.line})`:''}.`,`- 학생 영향: ${r.review.impact}.`,`- 추정 원인: ${r.review.cause} (${r.review.source}).`,`- 수정 난이도: ${r.review.difficulty}. 권장 처리: ${r.review.recommendation}.`);
}
md.push('', '## 의도적 차이와 미지원의 구분','', '- 큰 정수, 제한된 factorial, 재귀/명령/출력/컬렉션 제한, VFS 경로, 실행 시작 모듈 스냅샷, 순환 import 차단, Mulberry32 난수열, 고정 시계, map 내부 input 제한은 분리 기록했다.', '- dict.keys/values/items는 동적 view가 아닌 스냅샷. 중첩 언패킹은 오류 때 전체 대상 변경을 막는 기존 정책이 CPython과 다름.', '- 다중 상속·데코레이터·property·descriptor·메타클래스·연산자 오버로딩·복소수·bare * 키워드 전용 인수·iter/next·상대/와일드카드/동적 import·제너레이터 표현식·x 형식 지정은 이번 사례에서 미지원으로 분류.', '- descriptor는 SyntaxError로 거절되지 않고 다른 객체 결과로 조용히 완료한다. 미지원 구문이 항상 명시적으로 거절되는 것은 아니다.', '- 기본 객체/범위 표현과 동등한 문자열 따옴표 선택은 의미를 보존하는 표시 차이. 반면 개행/탭/역슬래시 repr 누락과 Unicode 파일 글자 수는 결함으로 기록했다.', '', '## 실제 브라우저 검사','', `- 로컬 원본 프로덕션 빌드, Edge ${b.browser}. **대표 ${b.representativeCases}개 × PC/모바일 = ${b.executions}회** 실제 CodeMirror 코드 교체 확인 후 실행.`, `- 측정 VM과 UI/Worker stdout·오류 위치 일치 ${b.results.filter(r=>r.outputMatch&&r.errorMatch).length}/${b.executions}; 내부 pageerror ${b.errors.length}개. 이는 CPython 일치 74건이라는 뜻이 아니며, 이미 측정된 결함도 동일하게 재현됨.`, '- 큰 정수·소수·평가 순서·loop else·재귀·finally·집합·람다 정렬·상속·모듈 오류·math·입력·파일·turtle 포함.', '- 출력·반복·명령·turtle 제한 자동 종료, 입력 대기 중 중지, CPU 실행 중 중지 및 매번 다음 일반 프로그램 실행 확인. 두 화면에서 미저장 helper.py 초안 999 대신 저장값 3 import 확인.', '- 새 격리 브라우저 컨텍스트만 사용. 기존 사용자 프로필/IndexedDB는 열거나 변경하지 않음. 테스트용 VFS 파일은 격리 컨텍스트에만 저장.', '- screenshots: artifacts/python-compatibility-browser/audit-1440x900.png 및 audit-360x800.png. 두 화면에 가로 넘침 없음. 화면 직접 확인.', '', '## 기존 검증 및 변경 보호','', '- npm test: 기존 **882/882**, 32개 테스트 파일 통과. 기존 테스트 수정 없음.', '- npm run build: TypeScript/Vite 프로덕션 빌드 성공. 의존성·버전·소스 변경 없음.', '- git tracked diff는 비어 있음. 새 작업은 audit/python-compatibility 및 ignored artifacts 아래뿐. 커밋·push·배포·태그·Release 없음.', '', '## 최종 지원 설명','', '**안심하고 사용할 수 있는 범위:** 이번 검사에서 확인한 안전 정수 범위의 일반 연산, 기본 조건·반복, 정상적인 함수·재귀 깊이 범위, 예외/finally, 기본 클래스·단일 상속, 저장된 모듈, 명시적 저장 및 일반 UTF-8 텍스트 수업 예제.', '', '**주의가 필요한 범위:** 입력 문자열→int 검증, 소수 //·%·divmod, 비교 연쇄 부작용, 빈 range 조건, 컬렉션 순서 비교·반복 중 수정, 리스트 += 공유 참조, 호출 결과 대상/슬라이스 대입, map 결합 메서드, 세부 예외 클래스와 일부 위치, Unicode 파일 읽기/길이, CRLF와 컬렉션 repr. 통과 사례만으로 이러한 주변 경계까지 일반화하지 않아야 한다.', '', '**지원하지 않는 범위:** 임의 정밀도 정수, CPython 난수열 동일성, 전체 표준 라이브러리·전체 turtle, 패키지/외부 라이브러리, 제너레이터·비동기·데코레이터·다중 상속·메타클래스·descriptor 등 고급 기능, EUC-KR 쓰기. 일부 미지원 코드가 명확히 거절되지 않을 수 있다.', '', '## 파일별 원시 결과 인덱스','', '| ID | 분야 | 분류 | 차이 |','|---|---|---|---|');
for(const r of d.results)md.push(`| ${r.id} | ${r.category} | ${r.classification} | ${r.differences.join(', ')|| (r.cpython.skipped?'CPython 미실행':'—')} |`);
md.splice(md.indexOf('## 비교 기준과 재현 방법')+2,0,'CSV의 cpythonStdoutJson/vmStdoutJson 열은 JSON 문자열 표현이다. 줄바꿈·따옴표·큰 정수 문자열·잘못된 단독 surrogate까지 손실 없이 보존한다. JSON.parse로 원래 stdout을 얻을 수 있다. CSV를 숫자 열로 자동 변환하지 않아야 한다.','');
await writeFile(path+'.md',md.join('\n')+'\n');
console.log(JSON.stringify({total:d.total,counts:d.counts,severity:sev,groups:d.defectGroups.length,browser:b.executions},null,2));
