import type { StudentError } from "./token";
export type SourcePoint = { line: number; column: number };
export type UnpackPattern = { kind: "leaf" } | { kind: "star"; target: UnpackPattern } | { kind: "sequence"; children: UnpackPattern[] };
export type Instruction =
  | ({ op: "sort_values"; count: number; reverse: boolean; inplace: boolean } & SourcePoint)
  | ({ op: "import_module"; module: string; member?: string } & SourcePoint)
  | ({ op: "constant"; value: unknown } & SourcePoint)
  | ({ op: "load"; name: string } & SourcePoint)
  | ({ op: "dup" | "dup_two" } & SourcePoint)
  | ({ op: "store"; name: string } & SourcePoint)
  | ({ op: "store_keep"; name: string } & SourcePoint)
  | ({ op: "unary"; operator: string } & SourcePoint)
  | ({ op: "binary"; operator: string } & SourcePoint)
  | ({ op: "compare"; operators: string[]; count: number } & SourcePoint)
  | ({ op: "call"; name: string; argc: number; keywords: string[]; spreads?: boolean[] } & SourcePoint)
  | ({ op: "call_value"; argc: number; keywords: string[]; spreads?: boolean[] } & SourcePoint)
  | ({ op: "make_function"; name: string; params: { name: string; kind?: import("./ast").ParameterKind; hasDefault: boolean }[]; localNames: string[]; globals: string[]; nonlocals?: string[]; bytecode: Bytecode } & SourcePoint)
  | ({ op: "make_class"; name: string; bytecode: Bytecode; hasParent?: boolean } & SourcePoint)
  | ({ op: "return_value" } & SourcePoint)
  | ({ op: "build_string"; count: number } & SourcePoint)
  | ({ op: "format_value"; format: import("./ast").FStringFormat } & SourcePoint)
  | ({ op: "pop" } & SourcePoint)
  | ({ op: "jump"; target: number } & SourcePoint)
  | ({ op: "jump_if_false"; target: number } & SourcePoint)
  | ({ op: "jump_if_false_keep"; target: number } & SourcePoint)
  | ({ op: "jump_if_true_keep"; target: number } & SourcePoint)
  | ({ op: "iter_prepare" } & SourcePoint)
  | ({ op: "iter_next"; names: string[]; target: number; pattern?: UnpackPattern } & SourcePoint)
  | ({ op: "build_list" | "build_tuple" | "build_set"; count: number; spreads?: boolean[] } & SourcePoint)
  | ({ op: "delete_name"; name: string } & SourcePoint)
  | ({ op: "delete_subscript" } & SourcePoint)
  | ({ op: "build_dict"; count: number; spreads?: boolean[] } & SourcePoint)
  | ({ op: "load_subscript" } & SourcePoint)
  | ({ op: "store_subscript" } & SourcePoint)
  | ({ op: "store_subscript_keep" } & SourcePoint)
  | ({ op: "build_slice"; hasStart: boolean; hasStop: boolean; hasStep: boolean } & SourcePoint)
  | ({ op: "load_attr"; name: string } & SourcePoint)
  | ({ op: "store_attr"; name: string } & SourcePoint)
  | ({ op: "store_attr_keep"; name: string } & SourcePoint)
  | ({ op: "call_method"; name: string; argc: number; keywords: string[]; spreads?: boolean[] } & SourcePoint)
  | ({ op: "enter_with"; name: string; end: number } & SourcePoint)
  | ({ op: "exit_with" } & SourcePoint)
  | ({ op: "setup_except"; end: number; handlers: { type?: string; name?: string; target: number; end: number }[] } & SourcePoint)
  | ({ op: "setup_finally"; target: number; end: number } & SourcePoint)
  | ({ op: "end_handler" | "end_finally" } & SourcePoint)
  | ({ op: "raise"; hasValue: boolean } & SourcePoint)
  | ({ op: "pop_except" } & SourcePoint)
  | ({ op: "unpack"; names: string[]; pattern?: UnpackPattern } & SourcePoint)
  | ({ op: "run_comprehension"; bytecode: Bytecode; localNames: string[]; iterableName: string } & SourcePoint)
  | ({ op: "loop_guard" } & SourcePoint);
export interface Bytecode { instructions: Instruction[]; }
export type CompileResult = { bytecode: Bytecode } | { error: StudentError };
