import type { StudentError } from "./token";
export type SourcePoint = { line: number; column: number };
export type Instruction =
  | ({ op: "constant"; value: unknown } & SourcePoint)
  | ({ op: "load"; name: string } & SourcePoint)
  | ({ op: "dup" } & SourcePoint)
  | ({ op: "store"; name: string } & SourcePoint)
  | ({ op: "store_keep"; name: string } & SourcePoint)
  | ({ op: "unary"; operator: string } & SourcePoint)
  | ({ op: "binary"; operator: string } & SourcePoint)
  | ({ op: "compare"; operators: string[]; count: number } & SourcePoint)
  | ({ op: "call"; name: string; argc: number; keywords: string[] } & SourcePoint)
  | ({ op: "call_value"; argc: number; keywords: string[] } & SourcePoint)
  | ({ op: "make_function"; name: string; params: { name: string; hasDefault: boolean }[]; localNames: string[]; globals: string[]; bytecode: Bytecode } & SourcePoint)
  | ({ op: "make_class"; name: string; bytecode: Bytecode } & SourcePoint)
  | ({ op: "return_value" } & SourcePoint)
  | ({ op: "build_string"; count: number } & SourcePoint)
  | ({ op: "pop" } & SourcePoint)
  | ({ op: "jump"; target: number } & SourcePoint)
  | ({ op: "jump_if_false"; target: number } & SourcePoint)
  | ({ op: "jump_if_false_keep"; target: number } & SourcePoint)
  | ({ op: "jump_if_true_keep"; target: number } & SourcePoint)
  | ({ op: "iter_prepare" } & SourcePoint)
  | ({ op: "iter_next"; names: string[]; target: number } & SourcePoint)
  | ({ op: "build_list" | "build_tuple"; count: number } & SourcePoint)
  | ({ op: "build_dict"; count: number } & SourcePoint)
  | ({ op: "load_subscript" } & SourcePoint)
  | ({ op: "store_subscript" } & SourcePoint)
  | ({ op: "store_subscript_keep" } & SourcePoint)
  | ({ op: "build_slice"; hasStart: boolean; hasStop: boolean; hasStep: boolean } & SourcePoint)
  | ({ op: "load_attr"; name: string } & SourcePoint)
  | ({ op: "store_attr"; name: string } & SourcePoint)
  | ({ op: "store_attr_keep"; name: string } & SourcePoint)
  | ({ op: "call_method"; name: string; argc: number } & SourcePoint)
  | ({ op: "enter_with"; name: string } & SourcePoint)
  | ({ op: "exit_with" } & SourcePoint)
  | ({ op: "setup_except"; handlers: { type?: string; name?: string; target: number }[] } & SourcePoint)
  | ({ op: "pop_except" } & SourcePoint)
  | ({ op: "clear_exception"; name: string } & SourcePoint)
  | ({ op: "unpack"; names: string[] } & SourcePoint)
  | ({ op: "loop_guard" } & SourcePoint);
export interface Bytecode { instructions: Instruction[]; }
export type CompileResult = { bytecode: Bytecode } | { error: StudentError };
