import type { LearningExample } from "./model";

// Original teaching examples: only page/concept associations refer to the textbook.
// Stable order follows the local audit's 56 entries; no source or publisher data is embedded.
function example(page: number, order: number, slug: string, title: string, topics: string[], code: string, expectedOutput?: string, extra: Partial<LearningExample> = {}): LearningExample {
  return { id: `page-${page}-${slug}`, collection: "textbook", page, order, title,
    summary: `${title} — ${topics.join(" · ")}의 동작을 작은 프로그램으로 살펴봅니다.`, topics,
    status: "ready", code, suggestedFileName: `${page}-${slug}.py`, expectedOutput, ...extra };
}
const variables = ["변수·자료형"], io = ["입력·출력"], lists = ["리스트·컬렉션"], loops = ["반복문"], conditions = ["조건문"], functions = ["함수"], classes = ["클래스"], files = ["파일 입출력"];
const input = (answers: string[]): Partial<LearningExample> => ({ status: "input", inputGuide: answers });
const corrected = (note: string): Partial<LearningExample> => ({ status: "corrected", correctionNote: note });
export const TEXTBOOK_EXAMPLES: readonly LearningExample[] = [
  example(120, 1, "accumulate", "변수에 계산 결과 저장", variables, 'distance = 8\ndistance = distance + 4\ntotal = 30 + distance\nprint(distance, total)', '12 42\n'),
  example(120, 2, "reassign", "값을 바꾸면 자료형도 바뀌어요", variables, 'item = 7\nprint(type(item))\nitem = "별"\nprint(type(item))', "<class 'int'>\n<class 'str'>\n"),
  example(120, 3, "types", "여러 자료형 살펴보기", variables, 'values = [8, 2.5, "하늘", True, [1], (2,), {"색": "파랑"}]\nfor value in values:\n    print(type(value))'),
  example(121, 1, "korean-names", "한글 변수로 기록하기", variables, '꽃이름 = "민들레"\n꽃잎수 = 12\n길이 = 4.5\n관찰완료 = True\nprint(꽃이름, 꽃잎수, 길이, 관찰완료)', '민들레 12 4.5 True\n'),
  example(121, 2, "float", "실수로 길이 계산", variables, 'radius = 3\npi = 3.14\nperimeter = 2 * pi * radius\nprint(perimeter)', '18.84\n'),
  example(121, 3, "conversion", "문자와 숫자를 더하기 전에", variables, 'count, extra = 12, "8"\nprint(count + int(extra))', '20\n', corrected('문자열과 정수는 바로 더할 수 없어 int()로 숫자로 변환합니다.')),
  example(122, 1, "greeting", "이름을 입력받아 인사", io, 'name = input("이름: ")\nprint(f"안녕하세요, {name}")', '안녕하세요, 민수\n', input(["민수"])),
  example(122, 2, "print", "여러 값을 한 줄에 출력", io, 'fruit = "자두"\nprint("과일:", fruit)\nprint("가격:", 800 * 4)', '과일: 자두\n가격: 3200\n'),
  example(123, 1, "write", "메모 파일 쓰기", files, 'file = open("memo.txt", "w")\nfile.write("오늘은 맑음\\n")\nfile.close()\nprint("메모 작성 완료")', '메모 작성 완료\n'),
  example(123, 2, "read", "작성한 메모 다시 읽기", files, 'with open("memo.txt", "w") as file:\n    file.write("별을 관찰했습니다.")\nwith open("memo.txt", "r") as file:\n    print(file.read())', '별을 관찰했습니다.\n'),
  example(124, 1, "area", "입력으로 넓이 구하기", [...io, ...variables], 'side = int(input("한 변 길이: "))\nprint("넓이:", side * side)', '넓이: 36\n', input(["6"])),
  example(124, 2, "journal", "관찰 일지 덧붙이기", [...files, ...io], 'day = input("관찰 날짜: ")\nnote = input("관찰 내용: ")\nwith open("journal.txt", "a") as file:\n    file.write(day + ": " + note + "\\n")\nprint("일지에 추가했습니다.")', '일지에 추가했습니다.\n', input(["2026-09-01", "새싹이 났어요"])),
  example(124, 3, "csv", "작은 CSV 파일 읽기", [...files, ...loops], 'with open("observations.csv", "r", encoding="utf-8") as file:\n    file.readline()\n    for line in file.readlines():\n        columns = line.strip().split(",")\n        print(columns[0], columns[1])', '새싹 3\n꽃 5\n', { status: "data", dataFiles: [{ name: "observations.csv", content: "대상,개수\r\n새싹,3\r\n꽃,5\r\n", encoding: "utf-8" }] }),
  example(127, 1, "list", "목록에 숫자 모으기", lists, 'heights = [12, 17, 9, 21]\nprint(heights)', '[12, 17, 9, 21]\n'),
  example(127, 2, "list-update", "목록의 한 칸 고치기", lists, 'heights = [12, 17, 9]\nheights[1] = 18\nprint(heights)', '[12, 18, 9]\n'),
  example(127, 3, "append", "관찰값 수정하고 추가", lists, 'counts = [2, 4]\nprint(counts[0])\ncounts[0] = 3\ncounts.append(6)\nprint(counts)', '2\n[3, 4, 6]\n'),
  example(128, 1, "dictionary", "이름표로 값 찾기", lists, 'stock = {"연필": 5, "지우개": 3}\nprint(stock["연필"])\nstock["연필"] = 7\nstock["공책"] = 2\nprint(stock)', "5\n{'연필': 7, '지우개': 3, '공책': 2}\n"),
  example(128, 2, "dict-values", "딕셔너리로 색 기록", lists, 'colors = {"하늘": "파랑", "잎": "초록"}\nprint(colors)', "{'하늘': '파랑', '잎': '초록'}\n"),
  example(128, 3, "dict-update", "키를 찾아 값 수정", lists, 'colors = {"잎": "초록"}\ncolors["잎"] = "노랑"\nprint(colors["잎"])', '노랑\n'),
  example(128, 4, "dict-add", "새로운 키 추가", lists, 'colors = {"하늘": "파랑"}\ncolors["꽃"] = "분홍"\nprint(colors)', "{'하늘': '파랑', '꽃': '분홍'}\n"),
  example(129, 1, "matrix", "행과 열로 자료 찾기", lists, 'seats = [[1, 2], [3, 4]]\nprint(seats[1][0])\nseats[0][1] = 9\nprint(seats)', '3\n[[1, 9], [3, 4]]\n'),
  example(130, 1, "nested-dict", "중첩된 이름표", lists, 'garden = {"앞뜰": {"꽃": 4, "나무": 2}}\nprint(garden["앞뜰"]["꽃"])\ngarden["앞뜰"]["꽃"] = 6\nprint(garden["앞뜰"])', "4\n{'꽃': 6, '나무': 2}\n"),
  example(130, 2, "missing-key", "없는 키를 안전하게 처리", [...lists, "예외 처리"], 'stock = {"공책": 4}\ntry:\n    print(stock["물감"])\nexcept KeyError:\n    print("목록에 없는 물품입니다.")', '목록에 없는 물품입니다.\n', corrected('존재하지 않는 키를 조회하던 부분을 KeyError 처리로 감쌉니다.')),
  example(130, 3, "lookup", "입력한 키로 찾아보기", [...lists, ...io, "예외 처리"], 'garden = {"앞뜰": {"꽃": 4}}\nplace = input("장소: ")\nitem = input("대상: ")\ntry:\n    print(garden[place][item])\nexcept KeyError:\n    print("찾는 항목이 없습니다.")', '4\n', input(["앞뜰", "꽃"])),
  example(131, 1, "character", "묶인 속성 수정", lists, 'robot = {"탐사봇": {"전력": 80, "속도": 3}}\nrobot["탐사봇"]["전력"] = 90\nprint(robot["탐사봇"]["전력"])', '90\n'),
  example(131, 2, "graph", "연결되지 않은 칸 표현", lists, 'empty = None\nroutes = [[empty, 4], [2, empty]]\nprint(routes)', '[[None, 4], [2, None]]\n', corrected('정의되지 않은 이름 대신 None으로 연결이 없는 칸을 명시합니다.')),
  example(133, 1, "even", "홀수와 짝수 나누기", [...conditions, ...io], 'number = int(input("정수: "))\nif number % 2 == 0:\n    print("짝수")\nelse:\n    print("홀수")', '짝수\n', input(["8"])),
  example(133, 2, "if", "조건이 맞으면 안내", [...conditions, ...io], 'answer = input("전등을 켤까요? y/n: ")\nif answer == "y":\n    print("전등 켜짐")\nprint("확인 완료")', '전등 켜짐\n확인 완료\n', input(["y"])),
  example(134, 1, "elif", "세 가지 경우 구분", [...conditions, ...io], 'temperature = int(input("온도: "))\nif temperature > 0:\n    print("영상")\nelif temperature < 0:\n    print("영하")\nelse:\n    print("0도")', '영하\n', input(["-2"])),
  example(135, 1, "fee", "조건에 따라 비용 더하기", [...conditions, ...io], 'ticket = int(input("입장료: "))\nmember = input("회원 y/n: ")\nif member == "n":\n    ticket += 500\nprint(ticket)', '2500\n', input(["2000", "n"])),
  example(135, 2, "fee-elif", "여러 할인 조건", [...conditions, ...io], 'count = int(input("인원: "))\nmember = input("회원 y/n: ")\nfee = count * 2000\nif member == "y":\n    fee -= 500\nelif count >= 4:\n    fee -= 1000\nprint(fee)', '7000\n', input(["4", "n"])),
  example(136, 1, "nested-if", "중첩 조건과 변수 이름", conditions, 'height = 135\nready = True\nif ready:\n    if height >= 120:\n        print("탑승 준비 완료")\n    else:\n        print("키를 확인해 주세요.")', '탑승 준비 완료\n', corrected('철자가 다른 변수 참조를 앞에서 정의한 변수 이름으로 통일합니다.')),
  example(137, 1, "average", "반복해서 합계와 평균", [...loops, ...lists], 'values = [6, 8, 11]\ntotal = 0\nfor value in values:\n    total += value\nprint(total, f"{total / len(values):.2f}")', '25 8.33\n'),
  example(138, 1, "multiplication", "반복문 안의 f-string", loops, 'for number in range(1, 4):\n    print(f"7 × {number} = {7 * number}")', '7 × 1 = 7\n7 × 2 = 14\n7 × 3 = 21\n'),
  example(138, 2, "range", "범위를 정해 반복", loops, 'for step in range(2, 7, 2):\n    print(step)', '2\n4\n6\n'),
  example(139, 1, "questions", "질문 목록을 순서대로", [...loops, ...io], 'questions = ["좋아하는 색: ", "좋아하는 계절: "]\nfor question in questions:\n    answer = input(question)\n    print(f"기록: {answer}")', '기록: 파랑\n기록: 봄\n', input(["파랑", "봄"])),
  example(139, 2, "sort", "이웃한 두 값 교환", [...loops, ...lists, ...io], 'values = list(map(int, input("정수 세 개: ").split()))\nfor end in range(len(values) - 1, 0, -1):\n    for index in range(end):\n        if values[index] > values[index + 1]:\n            values[index], values[index + 1] = values[index + 1], values[index]\nprint(values)', '[2, 5, 9]\n', input(["9 2 5"])),
  example(140, 1, "random-guess", "난수와 입력 비교", ["random", ...loops, ...io], 'import random\nanswer = random.randint(1, 6)\nfor attempt in range(3):\n    guess = int(input("1~6 숫자, 종료는 0: "))\n    if guess == 0:\n        break\n    if guess == answer:\n        print("같은 수입니다.")\n        break\n    print("다른 수입니다.")\nprint("비교 종료")', undefined, input(["0"])),
  example(140, 2, "while", "횟수를 세며 반복", loops, 'remaining = 3\nwhile remaining > 0:\n    print(remaining)\n    remaining -= 1\nprint("출발")', '3\n2\n1\n출발\n'),
  example(141, 1, "password", "입력 반복을 제한하기", [...loops, ...io], 'opened = False\nfor attempt in range(3):\n    word = input("시작하려면 출발: ")\n    if word == "출발":\n        opened = True\n        print("문이 열렸습니다.")\n        break\nif not opened:\n    print("다음에 다시 시도하세요.")', '문이 열렸습니다.\n', input(["출발"])),
  example(141, 2, "break", "조건을 만나면 반복 끝", loops, 'for value in [3, 6, -1, 9]:\n    if value < 0:\n        break\n    print(value)', '3\n6\n'),
  example(141, 3, "continue", "필요 없는 값 건너뛰기", loops, 'for value in [3, -1, 6]:\n    if value < 0:\n        continue\n    print(value)', '3\n6\n'),
  example(142, 1, "random-loop", "무한 반복의 종료 조건", ["random", ...loops, ...io], 'import random\nwhile True:\n    print("주사위:", random.randint(1, 6))\n    if input("계속 y / 종료 n: ") == "n":\n        break\nprint("종료")', undefined, input(["n"])),
  example(143, 1, "grid", "리스트 내포로 격자 만들기", [...loops, ...lists, ...io], 'grid = [[0 for column in range(3)] for row in range(3)]\nposition = input("행 열 (0~2), 종료 n: ")\nif position != "n":\n    row, column = map(int, position.split())\n    if 0 <= row < 3 and 0 <= column < 3:\n        grid[row][column] = 1\nfor row in grid:\n    print(row)', '[0, 0, 0]\n[0, 0, 1]\n[0, 0, 0]\n', input(["1 2"])),
  example(144, 1, "sum-function", "계산을 함수로 묶기", [...functions, ...io], 'def total_to(limit):\n    result = 0\n    for number in range(1, limit + 1):\n        result += number\n    return result\nprint(total_to(int(input("끝 수: "))))', '21\n', input(["6"])),
  example(144, 2, "divisors", "함수 반환값 더하기", [...functions, ...loops], 'def divisor_count(number):\n    count = 0\n    for candidate in range(1, number + 1):\n        if number % candidate == 0:\n            count += 1\n    return count\nprint(divisor_count(6) + divisor_count(9))', '7\n'),
  example(145, 1, "menu", "메뉴를 함수로 나누기", [...functions, ...loops, ...io], 'total = 0\nprices = {"차": 1500, "물": 500}\ndef order(name):\n    global total\n    total += prices[name]\nwhile True:\n    choice = input("차 / 물 / 종료: ")\n    if choice == "종료":\n        break\n    if choice in prices:\n        order(choice)\nprint("합계:", total)', '합계: 1500\n', input(["차", "종료"])),
  example(148, 1, "constructor", "생성자로 객체 초기화", classes, 'class Plant:\n    def __init__(self, name, height):\n        self.name = name\n        self.height = height\nplant = Plant("강낭콩", 12)\nprint(plant.name, plant.height)', '강낭콩 12\n'),
  example(148, 2, "class-attribute", "클래스와 인스턴스 속성", classes, 'class Lamp:\n    color = "흰색"\nfirst = Lamp()\nsecond = Lamp()\nfirst.color = "노랑"\nprint(first.color, second.color)', '노랑 흰색\n'),
  example(149, 1, "object-use", "클래스 바깥에서 객체 사용", classes, 'class Basket:\n    def __init__(self):\n        self.items = []\n    def add(self, item):\n        self.items.append(item)\n        return len(self.items)\n    def __str__(self):\n        return f"물건 {len(self.items)}개"\nbasket = Basket()\nprint(basket.add("돋보기"))\nprint(basket)', '1\n물건 1개\n', corrected('실행문이 메서드 내부 return 뒤에 있던 들여쓰기를 바로잡아 클래스 바깥에서 객체를 생성합니다.')),
  example(149, 2, "date", "날짜와 객체의 속성", [...classes, "datetime"], 'from datetime import date\nclass Project:\n    def __init__(self, start_year):\n        self.start_year = start_year\n    def years(self):\n        return date.today().year - self.start_year\nproject = Project(2020)\nprint(project.start_year)\nprint(project.years())', undefined, corrected('초기화한 속성과 읽는 속성의 이름을 일치시킵니다. 경과 연수는 실행 날짜에 따라 달라집니다.')),
  example(150, 1, "number-game", "난수 목록과 클래스 활용 (150–151쪽)", ["random", ...classes, ...lists, ...io], 'import random\nclass Round:\n    def __init__(self):\n        self.values = random.sample(range(10), 3)\n    def show(self):\n        print(self.values)\nround = Round()\nname = input("참가자 이름: ")\nround.show()\nprint(f"{name}: 숫자 세 개를 관찰해 보세요.")\nprint(f"{\'완료\':^10}"); print("-" * 10)', undefined, input(["탐험가"])),
  example(152, 1, "runs", "같은 문자의 연속 횟수", [...functions, ...loops], 'def compress(text):\n    result = ""\n    previous = ""\n    count = 0\n    for letter in text:\n        if letter != previous and count > 0:\n            result += previous + str(count)\n            count = 0\n        previous = letter\n        count += 1\n    if count > 0:\n        result += previous + str(count)\n    return result\nprint(compress("XXYYYZ"))', 'X2Y3Z1\n'),
  example(153, 1, "turtle-square", "반복문으로 사각형 그리기", ["turtle", ...loops], 'import turtle\npen = turtle.Turtle()\npen.pencolor("blue")\npen.pensize(3)\nfor side in range(4):\n    pen.forward(80)\n    pen.right(90)\nturtle.done()', undefined, { expectedGraphic: "Canvas 중앙에서 시작하는 파란 사각형이 그려집니다." }),
  example(153, 2, "movie", "키워드 인수로 소개 카드", classes, 'class Movie:\n    def __init__(self, title, minutes):\n        self.title = title\n        self.minutes = minutes\n    def display(self):\n        print(f"제목: {self.title}")\n        print(f"길이: {self.minutes}분")\nmovie = Movie(minutes=25, title="별빛 여행")\nmovie.display()', '제목: 별빛 여행\n길이: 25분\n'),
  example(153, 3, "movie-list", "객체 안에 목록 보관 (지도서 연계)", [...classes, ...lists], 'class Screening:\n    def __init__(self, title, places):\n        self.title = title\n        self.places = places\n    def display(self):\n        print(f"{self.title}: {len(self.places)}곳")\nscreening = Screening(title="숲의 하루", places=["교실", "강당"])\nscreening.display()', '숲의 하루: 2곳\n'),
];
