import "./styles/app.css";
import { LearningEditor } from "./editor/editor";
import { checkedPut, IndexedDbFileStore, normalizeName, validFileName, type AppFile } from "./files/storage";
import { setupPwa } from "./pwa/register";
import type { FromWorker, ToWorker } from "./runtime/protocol";

const initialCode = `name = input("이름을 입력하세요: ")
age = int(input("나이를 입력하세요: "))

print("안녕하세요,", name)
print("내년에는", age + 1, "살입니다.")`;
const store = new IndexedDbFileStore();
const app = document.querySelector<HTMLDivElement>("#app")!;
app.innerHTML = `<main class="app"><header class="topbar"><div class="filename"><span class="current-name">main.py</span><span class="modified" aria-label="수정됨"></span></div><div class="actions"><button class="files-toggle" type="button">파일</button><button class="new-file" type="button">새 파일</button><button class="save" type="button">저장</button><button class="save-as" type="button">다른 이름으로</button><button class="import" type="button">가져오기</button><button class="export" type="button">내보내기</button><button class="delete-file" type="button">삭제</button><button class="stop" type="button" disabled>중지</button><button class="run" type="button">실행</button></div></header><section class="workspace"><aside class="file-panel" aria-label="파일 목록"><div class="panel-heading">파일</div><div class="file-list"></div></aside><section class="panel"><div class="panel-heading">코드 편집기</div><div class="editor-host"></div><div class="editor-tools"><button class="tab-button" type="button">Tab</button></div></section><section class="panel"><div class="panel-heading">실행 결과</div><button class="clear" type="button">결과 지우기</button><div class="console" aria-live="polite"><span class="console-empty">실행 결과가 여기에 표시됩니다.</span></div></section></section><div class="dialog-layer" hidden><section class="save-dialog" role="dialog" aria-modal="true" aria-labelledby="save-question"><p id="save-question">변경 사항을 저장하시겠습니까?</p><div><button data-choice="save" type="button">저장</button><button data-choice="discard" type="button">저장하지 않음</button><button data-choice="cancel" type="button">취소</button></div></section></div></main>`;
const appStatus = document.createElement("div"); appStatus.className = "app-status"; appStatus.setAttribute("aria-live", "polite"); appStatus.innerHTML = `<span class="connection-status"></span><span class="pwa-message" hidden></span><span class="ios-install-hint" hidden>공유 버튼을 누른 뒤 ‘홈 화면에 추가’를 선택하세요.</span><span class="update-notice" hidden>새 버전을 사용할 수 있습니다.</span><button class="update" type="button" hidden>업데이트</button><button class="install" type="button" hidden>앱 설치</button>`; const topbar = app.querySelector(".topbar")!; topbar.insertBefore(appStatus, topbar.querySelector(".actions"));
const nameLayer = document.createElement("div"); nameLayer.className = "dialog-layer"; nameLayer.hidden = true; nameLayer.innerHTML = `<section class="save-dialog" role="dialog" aria-modal="true" aria-label="파일 이름"><p class="name-question">파일 이름을 입력하세요.</p><input class="name-input" aria-label="파일 이름" /><div><button class="name-confirm" type="button">확인</button><button class="name-cancel" type="button">취소</button></div></section>`; app.querySelector(".app")!.append(nameLayer);
const host = app.querySelector<HTMLElement>(".editor-host")!, consoleEl = app.querySelector<HTMLElement>(".console")!;
const runButton = app.querySelector<HTMLButtonElement>(".run")!, stopButton = app.querySelector<HTMLButtonElement>(".stop")!, modified = app.querySelector<HTMLElement>(".modified")!, nameEl = app.querySelector<HTMLElement>(".current-name")!, filePanel = app.querySelector<HTMLElement>(".file-panel")!, fileList = app.querySelector<HTMLElement>(".file-list")!, dialog = app.querySelector<HTMLElement>(".dialog-layer")!;
const connectionEl = appStatus.querySelector<HTMLElement>(".connection-status")!, pwaMessage = appStatus.querySelector<HTMLElement>(".pwa-message")!, iosInstallHint = appStatus.querySelector<HTMLElement>(".ios-install-hint")!, updateNotice = appStatus.querySelector<HTMLElement>(".update-notice")!, updateButton = appStatus.querySelector<HTMLButtonElement>(".update")!, installButton = appStatus.querySelector<HTMLButtonElement>(".install")!;
let dirty = false, worker: Worker | undefined, editor: LearningEditor, currentName = "main.py";
let files = new Map<string, AppFile>();
const append = (text: string, className = "console-line") => { const node = document.createElement("span"); node.className = className; node.textContent = text; consoleEl.append(node); consoleEl.scrollTop = consoleEl.scrollHeight; };
const clearConsole = () => consoleEl.replaceChildren();
const status = (text: string) => append(text, "console-status");
const setRunning = (value: boolean) => { runButton.disabled = value; stopButton.disabled = !value; };
const setDirty = (value: boolean) => { dirty = value; modified.textContent = value ? " *" : ""; };
const typeLabel = (name: string) => name.split(".").at(-1)?.toUpperCase() ?? "파일";
const renderFiles = () => { fileList.replaceChildren(...[...files.values()].sort((a, b) => a.name.localeCompare(b.name, "ko")).map(file => { const button = document.createElement("button"); button.type = "button"; button.className = `file-item${file.name === currentName ? " selected" : ""}`; button.innerHTML = `<span></span><small>${typeLabel(file.name)}</small>`; button.querySelector("span")!.textContent = file.name; button.addEventListener("click", () => openFile(file.name)); return button; })); };
const save = async (name = currentName, content = editor.value): Promise<boolean> => { try { const file = { name, content, updatedAt: Date.now() }; await checkedPut(store, file); files.set(name, file); currentName = name; nameEl.textContent = name; setDirty(false); renderFiles(); return true; } catch { append("파일을 저장할 수 없습니다.", "console-error"); return false; } };
const chooseUnsaved = (): Promise<"save" | "discard" | "cancel"> => new Promise(resolve => { dialog.hidden = false; const done = (choice: "save" | "discard" | "cancel") => { dialog.hidden = true; dialog.querySelectorAll<HTMLButtonElement>("button").forEach(button => button.onclick = null); resolve(choice); }; dialog.querySelectorAll<HTMLButtonElement>("button").forEach(button => button.onclick = () => done(button.dataset.choice as "save" | "discard" | "cancel")); });
const askName = (question: string, value: string): Promise<string | undefined> => new Promise(resolve => { const input = nameLayer.querySelector<HTMLInputElement>(".name-input")!; nameLayer.querySelector<HTMLElement>(".name-question")!.textContent = question; input.value = value; nameLayer.hidden = false; input.focus(); const done = (result?: string) => { nameLayer.hidden = true; resolve(result); }; nameLayer.querySelector<HTMLButtonElement>(".name-confirm")!.onclick = () => done(input.value); nameLayer.querySelector<HTMLButtonElement>(".name-cancel")!.onclick = () => done(); });
const protect = async (next: () => void | Promise<void>): Promise<void> => { if (dirty) { const choice = await chooseUnsaved(); if (choice === "cancel") return; if (choice === "save" && !await save()) return; } await next(); };
const nextNewName = () => { let index = 1, name = "새 파일.py"; while (files.has(name)) name = `새 파일 ${++index}.py`; return name; };
async function openFile(name: string): Promise<void> { const file = files.get(name); if (!file || !name.endsWith(".py")) return; await protect(() => { currentName = name; nameEl.textContent = name; editor.setValue(file.content); setDirty(false); renderFiles(); }); }
const newFile = async () => protect(() => { currentName = nextNewName(); nameEl.textContent = currentName; editor.setValue(""); setDirty(false); renderFiles(); });
const saveAs = async () => { const entered = await askName("새 파일 이름을 입력하세요.", currentName); if (entered === undefined) return; const name = normalizeName(entered); if (!validFileName(name)) { window.alert("파일 이름이 올바르지 않습니다."); return; } if (files.has(name) && !window.confirm(`'${name}' 파일을 덮어쓸까요?`)) return; await save(name); };
const removeCurrent = async () => protect(async () => { if (!files.has(currentName) || !window.confirm(`'${currentName}' 파일을 삭제할까요?`)) return; try { await store.delete(currentName); files.delete(currentName); currentName = nextNewName(); nameEl.textContent = currentName; editor.setValue(""); setDirty(false); renderFiles(); } catch { append("파일을 삭제할 수 없습니다.", "console-error"); } });
const importFile = () => { const input = document.createElement("input"); input.type = "file"; input.accept = ".py,.txt,.csv,text/plain,text/csv"; input.onchange = async () => { const picked = input.files?.[0]; if (!picked || !/\.(py|txt|csv)$/i.test(picked.name)) return; const content = await picked.text(); let name = picked.name; if (files.has(name)) { const choice = window.prompt("같은 이름의 파일이 있습니다: 덮어쓰기 / 다른 이름 / 취소", "덮어쓰기"); if (choice === "취소" || choice === null) return; if (choice === "다른 이름") { const alternative = window.prompt("새 파일 이름", name); if (alternative === null) return; name = normalizeName(alternative); } } try { const file = { name, content, updatedAt: Date.now() }; await checkedPut(store, file); files.set(name, file); renderFiles(); if (name.endsWith(".py")) await openFile(name); } catch { append("파일을 가져올 수 없습니다.", "console-error"); } }; input.click(); };
const exportFile = () => { const blob = new Blob([editor.value], { type: "text/plain;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = currentName; link.click(); URL.revokeObjectURL(link.href); };
editor = new LearningEditor(host, initialCode, () => { if (!dirty) setDirty(true); editor.setError(null); });
app.querySelector<HTMLButtonElement>(".tab-button")!.addEventListener("click", () => editor.insertTab()); app.querySelector<HTMLButtonElement>(".clear")!.addEventListener("click", clearConsole); app.querySelector<HTMLButtonElement>(".new-file")!.addEventListener("click", newFile); app.querySelector<HTMLButtonElement>(".save")!.addEventListener("click", () => save()); app.querySelector<HTMLButtonElement>(".save-as")!.addEventListener("click", saveAs); app.querySelector<HTMLButtonElement>(".import")!.addEventListener("click", importFile); app.querySelector<HTMLButtonElement>(".export")!.addEventListener("click", exportFile); app.querySelector<HTMLButtonElement>(".delete-file")!.addEventListener("click", removeCurrent); app.querySelector<HTMLButtonElement>(".files-toggle")!.addEventListener("click", () => filePanel.classList.toggle("show"));
window.addEventListener("beforeunload", event => { if (dirty) event.preventDefault(); });
function showInput(prompt: string): void { const row = document.createElement("form"); row.className = "input-row"; row.innerHTML = `<span class="input-prompt"></span><input class="console-input" aria-label="프로그램 입력" autocomplete="off" /><button class="input-submit" type="submit">입력</button>`; row.querySelector<HTMLElement>(".input-prompt")!.textContent = prompt; const input = row.querySelector<HTMLInputElement>("input")!; row.addEventListener("submit", event => { event.preventDefault(); const value = input.value; const answer = document.createElement("span"); answer.className = "console-line"; answer.textContent = `${prompt}${value}\n`; row.replaceWith(answer); worker?.postMessage({ type: "input", value } satisfies ToWorker); }); consoleEl.append(row); input.focus({ preventScroll: false }); row.scrollIntoView({ block: "nearest" }); }
function finish(kind: "complete" | "stopped"): void { status(kind === "complete" ? "실행이 완료되었습니다." : "실행이 중지되었습니다."); setRunning(false); worker?.terminate(); worker = undefined; }
function receive(message: FromWorker): void { switch (message.type) { case "output": append(message.text); break; case "input-request": showInput(message.prompt); break; case "file-change": { const file = { name: message.name, content: message.content, updatedAt: Date.now() }; files.set(file.name, file); renderFiles(); checkedPut(store, file).catch(() => append("파일 변경을 저장할 수 없습니다.", "console-error")); break; } case "error": editor.setError(message.error.line); append(`${message.error.line}번째 줄: ${message.error.message}`, "console-error"); setRunning(false); worker?.terminate(); worker = undefined; break; case "complete": finish("complete"); break; case "stopped": finish("stopped"); break; } }
runButton.addEventListener("click", () => { worker?.terminate(); clearConsole(); editor.setError(null); setRunning(true); status("실행 중..."); worker = new Worker(new URL("./runtime/worker.ts", import.meta.url), { type: "module" }); worker.onmessage = ({ data }: MessageEvent<FromWorker>) => receive(data); worker.onerror = () => { append("실행 중 오류가 발생했습니다.", "console-error"); setRunning(false); worker?.terminate(); worker = undefined; }; worker.postMessage({ type: "run", code: editor.value, files: [...files.values()].map(file => ({ name: file.name, content: file.content })) } satisfies ToWorker); });
stopButton.addEventListener("click", () => worker?.postMessage({ type: "stop" } satisfies ToWorker));
store.list().then(saved => { files = new Map(saved.map(file => [file.name, file])); renderFiles(); }).catch(() => append("저장소를 열 수 없습니다.", "console-error"));
setupPwa({
  onConnection: text => { connectionEl.textContent = text; },
  onMessage: text => { pwaMessage.textContent = text; pwaMessage.hidden = false; },
  onIosInstallHint: () => { iosInstallHint.hidden = false; },
  onInstallAvailable: install => { installButton.hidden = false; installButton.onclick = async () => { await install(); installButton.hidden = true; }; },
  onUpdate: activate => {
    updateNotice.hidden = false; updateButton.hidden = false;
    updateButton.onclick = async () => {
      if (dirty) { const choice = await chooseUnsaved(); if (choice === "cancel") return; if (choice === "save" && !await save()) return; }
      updateButton.disabled = true; activate();
    };
  },
});
